### ISSUE TITLE
Running CI scully process not finishing.

### ISSUE THREAD

**Issue by darxx** [scullyio/scully#1202] opened 2021-01-14 23:32 UTC
### Description
Scully node js process never ends.
And files are generated. And if NodeJS process is killed by hand.
 All files can be deployed.

#### 🔬 Minimal Reproduction
Use GitLab docker container and run GitLab-runner container.
configure .gitlab-ci.yml.
script commands
<pre><core>
build-dev:
  stage: build
  script: 
     - time node --max-old-space-size=12096 ./node_modules/@angular/cli/bin/ng build --prod
     - time npm run scully -- --scanRoutes --noPrompt
</code></pre>

#### 💻Your Environment

**Angular Version:**

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.7
Node: 12.16.2
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.0.4
@angular/cli                    11.0.7
@angular/fire                   6.1.4
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/ng-lib": "^1.0.2",
    "@scullyio/scully": "^1.0.11",
</code></pre>

## 🔥 Exception or Error

<pre><code>

> Drowex@1.17.7 scully /home/gitlab-runner/builds/7Tta35YY/0/internal/pixelarttool
> scully "--scanRoutes" "--noPrompt"
logging with severity "warning"
using plugins from folder "./scully"
 ☺   new Angular build imported
Starting background servers with: node ./node_modules/@scullyio/scully/src/scully.js serve --tds false --pjf false --ls warning --project PixelArtTool
 ☺   Started servers in background
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
No configuration for route "/live/:id" found. Skipping
Route list created in files:
  "./src/assets/scully-routes.json",
  "/home/gitlab-runner/builds/7Tta35YY/0/internal/pixelarttool/dist/PixelArtTool-static/assets/scully-routes.json",
  "/home/gitlab-runner/builds/7Tta35YY/0/internal/pixelarttool/dist/PixelArtTool/assets/scully-routes.json"
</code></pre>

@SanderElias 
I can share a screen to make this case faster to reproduce.

**Comment by christseng89** [comment] 2021-01-15 07:15
Thanks, Darxx.  I got a similar issue for 'ng new hello-world' by using @angular@11.0.7.

ng new hello-world
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict No
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE hello-world/angular.json (3575 bytes)
CREATE hello-world/package.json (1201 bytes)
CREATE hello-world/README.md (1019 bytes)   
CREATE hello-world/tsconfig.json (458 bytes)
CREATE hello-world/tslint.json (3185 bytes) 
CREATE hello-world/.editorconfig (274 bytes)
CREATE hello-world/.gitignore (631 bytes)
CREATE hello-world/.browserslistrc (703 bytes)
CREATE hello-world/karma.conf.js (1428 bytes)
CREATE hello-world/tsconfig.app.json (287 bytes)
CREATE hello-world/tsconfig.spec.json (333 bytes)
CREATE hello-world/src/favicon.ico (948 bytes)
CREATE hello-world/src/index.html (296 bytes)
CREATE hello-world/src/main.ts (372 bytes)
CREATE hello-world/src/polyfills.ts (2826 bytes)
CREATE hello-world/src/styles.css (80 bytes)
CREATE hello-world/src/test.ts (753 bytes)
CREATE hello-world/src/assets/.gitkeep (0 bytes)
CREATE hello-world/src/environments/environment.prod.ts (51 bytes)
CREATE hello-world/src/environments/environment.ts (662 bytes)
CREATE hello-world/src/app/app.module.ts (314 bytes)
CREATE hello-world/src/app/app.component.html (25725 bytes)
CREATE hello-world/src/app/app.component.spec.ts (955 bytes)
CREATE hello-world/src/app/app.component.ts (215 bytes)
CREATE hello-world/src/app/app.component.css (0 bytes)
CREATE hello-world/e2e/protractor.conf.js (904 bytes)
CREATE hello-world/e2e/tsconfig.json (274 bytes)
CREATE hello-world/e2e/src/app.e2e-spec.ts (662 bytes)
CREATE hello-world/e2e/src/app.po.ts (274 bytes)
- Installing packages (yarn)...error Couldn't find package "@angular-devkit/architect@0.1100.7" required by "@angular-devkit/build-angular@~0.1100.7" on the "npm" registry.
Error: Couldn't find package "@angular-devkit/build-webpack@0.1100.7" required by "@angular-devkit/build-angular@~0.1100.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (c:\Program Files (x86)\Yarn\lib\cli.js:721:66)
    at new MessageError (c:\Program Files (x86)\Yarn\lib\cli.js:750:123)
    at PackageRequest.<anonymous> (c:\Program Files (x86)\Yarn\lib\cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (c:\Program Files (x86)\Yarn\lib\cli.js:310:30)
    at c:\Program Files (x86)\Yarn\lib\cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by SanderElias** [comment] 2021-01-15 09:15
@darxx duplicate of #924 
@christseng89 Scully doesn't work without the router. Also, you have a problem with the Angular CLI. try using it with npx, and a set version.
something like:
```bash
npx @angular/cli@latest new hello-world --routing --style=css
```

@darxx If this somehow a different issue, please let me know, and I happily reopen this issue

**Closed by SanderElias** 2021-01-15 09:15 UTC
Labels: bug
