### ISSUE TITLE
Scully stucks at step "Creating Route List: 3/3"

### ISSUE THREAD

**Issue by macervero** [scullyio/scully#892] opened 2020-08-27 17:26 UTC
### Description

Dear Scully Team,

I'm trying to get a static site for my Angular project with Scully so I follow the steps descrived at [Scully Installation](https://scully.io/docs/learn/getting-started/installation/) and [Scully Building](https://scully.io/docs/learn/getting-started/building/) docs.

The problem appears when I try to finally convert my project by the execution of `npm run scully`. This command keeps stucked at step _Creating Route List 3/3_.

Thank you in advance!

##### Creation of the project
```
$ ng new
? What name would you like to use for the new workspace and initial project? Scu
llyAngular-Project
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE ScullyAngular-Project/README.md (1038 bytes)
CREATE ScullyAngular-Project/.editorconfig (274 bytes)
CREATE ScullyAngular-Project/.gitignore (631 bytes)
CREATE ScullyAngular-Project/angular.json (3686 bytes)
CREATE ScullyAngular-Project/package.json (1274 bytes)
CREATE ScullyAngular-Project/tsconfig.base.json (458 bytes)
CREATE ScullyAngular-Project/tsconfig.json (426 bytes)
CREATE ScullyAngular-Project/tslint.json (3184 bytes)
CREATE ScullyAngular-Project/.browserslistrc (853 bytes)
CREATE ScullyAngular-Project/karma.conf.js (1033 bytes)
CREATE ScullyAngular-Project/tsconfig.app.json (292 bytes)
CREATE ScullyAngular-Project/tsconfig.spec.json (338 bytes)
CREATE ScullyAngular-Project/src/favicon.ico (948 bytes)
CREATE ScullyAngular-Project/src/index.html (306 bytes)
CREATE ScullyAngular-Project/src/main.ts (372 bytes)
CREATE ScullyAngular-Project/src/polyfills.ts (2835 bytes)
CREATE ScullyAngular-Project/src/styles.css (80 bytes)
CREATE ScullyAngular-Project/src/test.ts (753 bytes)
CREATE ScullyAngular-Project/src/assets/.gitkeep (0 bytes)
CREATE ScullyAngular-Project/src/environments/environment.prod.ts (51 bytes)
CREATE ScullyAngular-Project/src/environments/environment.ts (662 bytes)
CREATE ScullyAngular-Project/src/app/app-routing.module.ts (245 bytes)
CREATE ScullyAngular-Project/src/app/app.module.ts (393 bytes)
CREATE ScullyAngular-Project/src/app/app.component.css (0 bytes)
CREATE ScullyAngular-Project/src/app/app.component.html (25757 bytes)
CREATE ScullyAngular-Project/src/app/app.component.spec.ts (1104 bytes)
CREATE ScullyAngular-Project/src/app/app.component.ts (225 bytes)
CREATE ScullyAngular-Project/e2e/protractor.conf.js (869 bytes)
CREATE ScullyAngular-Project/e2e/tsconfig.json (299 bytes)
CREATE ScullyAngular-Project/e2e/src/app.e2e-spec.ts (654 bytes)
CREATE ScullyAngular-Project/e2e/src/app.po.ts (301 bytes)
✔ Packages installed successfully.
```

##### Adding Scully

```
$ ng add @scullyio/init
Installing packages for tooling via npm.
Installed packages for tooling via npm.
    Install ng-lib for Angular v9
    ✅️ Added dependency
UPDATE src/app/app.module.ts (466 bytes)
UPDATE src/polyfills.ts (3028 bytes)
UPDATE package.json (1394 bytes)
✔ Packages installed successfully.
    ✅️ Update package.json
    ✅️ Created scully configuration file in scully.ScullyAngular-Project.config.ts
CREATE scully.ScullyAngular-Project.config.ts (196 bytes)
UPDATE package.json (1454 bytes)
    ✅️ Update scully.ScullyAngular-Project.config.ts
CREATE scully/tsconfig.json (556 bytes)
CREATE scully/plugins/plugin.ts (294 bytes)
UPDATE scully.ScullyAngular-Project.config.ts (228 bytes)
```

##### Building the project

```
$ ng build
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @scullyio/ng-lib : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 59.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 146 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 12.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.39 MB [initial] [rendered]
Date: 2020-08-27T17:06:49.384Z - Hash: a0354ec191a1818f93e7 - Time: 5036ms
```

##### Generating static site with Scully

```
$ npm run scully

> scully-angular-project@0.0.0 scully /home/milana/ProvesScully/ScullyAngular-Project
> scully

 ☺   new Angular build imported
 ☺   Started servers in background
Would you allow Scully to collect anonymous errors to improve our services? (Y/n)n
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
Route list created in files:
  "./dist/static/assets/scully-routes.json",
  "/home/milana/ProvesScully/ScullyAngular-Project/dist/ScullyAngular-Project/assets/scully-routes.json",
  "/home/milana/ProvesScully/ScullyAngular-Project/src/assets/scully-routes.json"

⠴ Creating Route List: 3/3
```

#### 💻Your Environment

**Operative System:** 

<pre><code>
Debian 10.5.0 - Buster

$uname -a
Linux MyPC 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
</pre></code>

**NodeJS version:** 

<pre><code>
$node -v
v14.9.0
</pre></code>

**Angular Version:**

<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.8
Node: 14.9.0
OS: linux x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Scully Version:**

<pre><code>
{
  "name": "scully-angular-project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.14",
    "@angular/common": "~10.0.14",
    "@angular/compiler": "~10.0.14",
    "@angular/core": "~10.0.14",
    "@angular/forms": "~10.0.14",
    "@angular/platform-browser": "~10.0.14",
    "@angular/platform-browser-dynamic": "~10.0.14",
    "@angular/router": "~10.0.14",
    "@scullyio/init": "^1.0.0-beta.3",
    "@scullyio/ng-lib": "^1.0.0-beta.2",
    "@scullyio/scully": "^1.0.0-beta.2",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.8",
    "@angular/cli": "~10.0.8",
    "@angular/compiler-cli": "~10.0.14",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}
</code></pre>

## 🔥 Exception or Error

<pre><code>
$ npm run scully

> scully-angular-project@0.0.0 scully /home/milana/ProvesScully/ScullyAngular-Project
> scully

 ☺   new Angular build imported
 ☺   Started servers in background
Would you allow Scully to collect anonymous errors to improve our services? (Y/n)n
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
Route list created in files:
  "./dist/static/assets/scully-routes.json",
  "/home/milana/ProvesScully/ScullyAngular-Project/dist/ScullyAngular-Project/assets/scully-routes.json",
  "/home/milana/ProvesScully/ScullyAngular-Project/src/assets/scully-routes.json"

⠴ Creating Route List: 3/3
</code></pre>

**Comment by koshyviv** [comment] 2020-08-28 06:23
Im facing the same issue - it works fine on my local, but whenever its run on our deployed containers it gets stuck.
Have tried with all beta versions (0,1,3)

Local
```
> offset-portal@0.0.0 scully /home/vivek/Documents/WORK/GreenStory/AdminApp/admin-api/scully
> scully

 ☺   new Angular build imported
⠙ Background servers already running.
Would you allow Scully to collect anonymous errors to improve our services? (Y/n)n
Finding all routes in application.
traversing app for routes
⠹ Loading guess-parser 
We encountered a problem while reading the routes from your applications source.
This might happen when there are lazy-loaded routes, that are not loaded,
Or when there are paths we can not resolve statically.
Check the routes in your app, rebuild and retry.
(You can inspect the error by passing the --showGuessError flag

When there are extraRoutes in your config, we will still try to render those.


Pull in data to create additional routes.
Route list created in files:
  "./dist/static/assets/scully-routes.json",
  "/xxxx/scully/dist/offset-portal/browser/assets/scully-routes.json",
  "/xxxxi/scully/src/assets/scully-routes.json"

Route "/project/32" rendered into file: "./dist/static/project/32/index.html"
Route "/" rendered into file: "./dist/static/index.html"
⠙ calculate timings TypeError: Object.fromEntries is not a function
    at PerformanceObserver.<anonymous> (/xxxx/scully/node_modules/@scullyio/scully/lib/utils/startup.js:86:34)
    at PerformanceObserver.runInAsyncScope (async_hooks.js:188:21)
    at PerformanceObserver.doNotify (perf_hooks.js:453:8)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```


Container
```
> offset-portal@0.0.0 scully /usr/src/app/scully
	
> scully
	
☺ new Angular build imported
	
☺ Started servers in background
		
Finding all routes in application.
	

----------------------------------
	
Using stored unhandled routes!.
	
To discover new routes in the angular app use "npm run scully -- --scanRoutes"

----------------------------------
Pull in data to create additional routes.
Route list created in files:
"./dist/static/assets/scully-routes.json",
"/usr/src/app/scully/dist/offset-portal/browser/assets/scully-routes.json",
"/usr/src/app/scully/src/assets/scully-routes.json"
```

**Comment by SanderElias** [comment] 2020-08-28 08:29
@jorgeucano is looking into this issue. We are investigating the root cause of this.

**Comment by jorgeucano** [comment] 2020-08-28 12:22
Hello @koshyviv the error `⠙ calculate timings TypeError: Object.fromEntries is not a function` come from the node version... Please use node 12

**Comment by macervero** [comment] 2020-08-29 18:31
I've tried Node versions 12 & 10 but both ot them stucks at the same point _⠴ Creating Route List: 3/3_.
Does somebody finds a solution?

**Comment by jorgeucano** [comment] 2020-08-31 11:33
@macervero I check the error and is from node 10, can you update Scully and try again with node  >= 12.13.0

**Comment by SanderElias** [comment] 2020-08-31 11:36
@macervero I'm running on Ubuntu 20. and currently on node 14.8, and I can't reproduce your issue.
If you can provide us with a way we can reproduce the issue, we can fix it.

**Comment by neryortez** [comment] 2020-08-31 13:29
@macervero 
Remember that when you change versions of node/npm you have to reinstall your dependencies.
Delete the node_modules folder and the package-lock.json file. And run npm i.

**Comment by macervero** [comment] 2020-08-31 17:00
> @macervero I check the error and is from node 10, can you update Scully and try again with node >= 12.13.0

Is there any special command to update Scully? Or this step consists on deleting node_modules/package-lock.json and execute command `npm install`, as proposed by @neryortez?

If it only consists on deleting and `npm install` it's what I've done and the problem persists...

I couldn't understand what is happening... Could it be a problem with Chromium version?

**Comment by macervero** [comment] 2020-08-31 17:05
> f you can provide us with a way we can reproduce the issue, we can fix it.

Could I provide you a Dokerfile?
I'm running it locally, but I've also tested it on Docker and the process sticks at the same point.

**Comment by neryortez** [comment] 2020-08-31 17:06
@macervero 
Wait a minute... The error that is resolved by using node > 12.13 is the  `⠙ calculate timings TypeError: Object.fromEntries is not a function`
You seem to be having another issue.
Providing a reproduceable would help to find it.

**Comment by macervero** [comment] 2020-09-01 11:44
@neryortez, perfect! So I provide you a Dockerfile!

Inside this [folder](https://www.dropbox.com/s/vg11ed9jxntoybg/Scully.zip?dl=0) you will find a Dockerfile and also the corresponding exportation of the docker image.
To run the container you just need to execute:

`docker run -it scullyi`

Once you are inside docker container, you can do a `ls` command so you will see that an angular project has been prepared (`ng build --prod` has been already done). So you only need to execute

`npm run scully`

to reproduce the error.

Thank you all in advance!!!!

**Comment by etavener** [comment] 2020-09-01 14:36
I've just done a fresh npm install (after deleting the package-lock) and I'm getting this issue. I'm not running docker

**Comment by amycdurbin** [comment] 2020-09-01 14:46
Related to #844

**Comment by etavener** [comment] 2020-09-01 14:59
I switched back to node 10.14.1 and I've done a fresh npm install and now it's working again. Something to do with installing on node 12.

**Comment by macervero** [comment] 2020-09-03 14:26
Dear team, could you reproduce the error through the given Dockerfile?

**Comment by ngdevelop-tech** [comment] 2020-09-10 05:06
Same issue happening with me.

When I execute `npm run scully` command it is getting stuck at `Creating Route List 3/3`
![image](https://user-images.githubusercontent.com/34959339/92683670-19dc7400-f351-11ea-866b-37ad4ca104eb.png)

**Version Details :**
Node : v12.17.0

**Dependencies**
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@scullyio/init": "^1.0.0",
    "@scullyio/ng-lib": "^1.0.0-beta.1",
    "@scullyio/scully": "^1.0.0-beta.5",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"

**Comment by SanderElias** [comment] 2020-09-10 08:34
@ngdevelop-tech they adding the `--host="0.0.0.0" cmd-line flag

**Comment by becjon** [comment] 2020-09-10 11:01
Same issue happening with me. Adding `--host="0.0.0.0" cmd-line flag did not change the behavior .

**Comment by jorgeucano** [comment] 2020-09-10 13:44
We are working to fix this issue :) ...

**Comment by jorgeucano** [comment] 2020-09-11 13:42
We found the issue with WSL and some Linux distros... I added two commands for support puppeteer in these cases.

Here in [WSL Pre-Requisites](https://scully.io/docs/learn/getting-started/installation/) have the command and config your project need for WSL or a Linux distro with this "issue"


![Capture](https://user-images.githubusercontent.com/5982204/92932406-3f35b480-f41b-11ea-8e81-c7d77198e9df.PNG)

**Closed by jorgeucano** 2020-09-11 13:42 UTC
Labels: bug, can't reproduce

**Comment by moritz31** [comment] 2020-09-15 12:37
@jorgeucano thanks for providing the wsl details. I try to get this working in a docker container but got the same issue as described. Is it possible that for docker there is an similar issue. The config for wsl didn't solved it. 

Angular: 10
scully 1.0.0-beta.6

Some strange issue, the puppeteer version 3.3 with scully does not work locally, i need to install version 5.3 to make it work local, maybe this is another issue ? 

Is there a way to make this more verbose so that we see what is going on ?

**Comment by jorgeucano** [comment] 2020-09-15 13:22
@moritz31 I will test with @SanderElias, Can you create another issue for the docker problem so, we can track better?

**Comment by moritz31** [comment] 2020-09-15 13:31
https://github.com/scullyio/scully/issues/924

**Comment by victorfrederiknielsen** [comment] 2020-09-15 13:47
I have the same problem on WSL2, Windows Insider build. 

scully.*.config.ts
```
import { ScullyConfig } from '@scullyio/scully';
export const config: ScullyConfig = {
  projectRoot: "./src",
  projectName: "<projectName>",
  outDir: 'dist/static',
  routes: {},
  puppeteerLaunchOptions: {
    args: [
      "--disable-gpu",
      "--renderer",
      "--no-sandbox",
      "--no-service-autorun",
      "--no-experiments",
      "--no-default-browser-check",
      "--disable-dev-shm-usage",
      "--disable-setuid-sandbox",
      "--no-first-run",
      "--no-zygote",
      "--single-process",
      "--disable-extensions"    
    ]
  }
};
```

generated scully-routes.json
```
[{"route":"/"}]
```

`(sudo) npm run scully`
```**********************************************************
**********************************************************
You are using "WLS" as a terminal, if you get an
error please read the pre-requisites for Microsoft WLS.
https://scullyio.firebaseapp.com/docs/learn/getting-started/installation/
**********************************************************
**********************************************************
      
using plugins from folder "./scully"
 ☺   new Angular build imported
⠙ Background servers already running.
Finding all routes in application.
⠙ warming up 
----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
Route list created in files:
  "./dist/static/assets/scully-routes.json",
  "/home/vfn/lobster/LobsterOps/Web/UI/dist/build/assets/scully-routes.json",
  "/home/vfn/lobster/LobsterOps/Web/UI/src/assets/scully-routes.json"

⠦ Creating Route List: 3/3
```

**Comment by jorgeucano** [comment] 2020-09-15 13:51
@victorfrederiknielsen Do you install chrome into the WSL? 
``` 
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

**Comment by victorfrederiknielsen** [comment] 2020-09-15 13:54
Yes, I followed the guide for WSL.

Reinstalling:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'google-chrome-stable' instead of './google-chrome-stable_current_amd64.deb'
google-chrome-stable is already the newest version (85.0.4183.102-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
Need to get 0 B/226 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
```


This is what happens when I do --scanRoutes. Let me try with the --showGuessError flag
```
 npm run scully -- --scanRoutes

> lobster-ops-website@1.0.0 scully /home/vfn/lobster/***
> scully --scanRoutes


**********************************************************
**********************************************************
You are using "WLS" as a terminal, if you get an
error please read the pre-requisites for Microsoft WLS.
https://scullyio.firebaseapp.com/docs/learn/getting-started/installation/
**********************************************************
**********************************************************
      
using plugins from folder "./scully"
⠙ Background servers already running.
Finding all routes in application.
traversing app for routes
We could not find "../tsconfig.app.json". Using the apps source folder as source. This might lead to unpredictable results
⠙ Loading guess-parser 
We encountered a problem while reading the routes from your applications source.
This might happen when there are lazy-loaded routes, that are not loaded,
Or when there are paths we can not resolve statically.
Check the routes in your app, rebuild and retry.
(You can inspect the error by passing the --showGuessError flag

When there are extraRoutes in your config, we will still try to render those.


Pull in data to create additional routes.
Could not write routes to files:
  "./dist/static/assets/scully-routes.json",
  "/home/vfn/lobster/LobsterOps/Web/UI/dist/build/assets/scully-routes.json",
  "/home/vfn/lobster/LobsterOps/Web/UI/src/assets/scully-routes.json"

⠹ Creating Route List: 1/3(node:27409) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
⠸ Creating Route List: 1/3
```

**Comment by IStep95** [comment] 2020-10-03 20:39
I had the same error with node v10.15.0, and change the node version to v12.18.3 and everything worked.

**Comment by auxilien0** [comment] 2020-12-02 14:03
1. npm run build --prod
2. ng serve
3. (open new terminal)
4. npm run scully

This worked for me, do not know about you guys
`"@scullyio/scully": "^1.0.5",`
