### ISSUE TITLE
The process "2488" not found

### ISSUE THREAD

**Issue by Ferie** [scullyio/scully#732] opened 2020-07-10 23:23 UTC
## 🐞 Bug report

ERROR: The process "2488" not found.

### Description

I have no indication of what to do next in this context.

#### 🔬 Minimal Reproduction

I have followed all the steps [in the getting started](https://scully.io/docs/getting-started/) guide and when reaching the point to run `ng add @scullyio/init` I have these logs

```
$ npm run scully

> <project-name>@0.1.0 scully <local-path>
> scully

 âº   new Angular build imported
 âº   Started servers in background
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
No configuration for route "/details/:name" found. Skipping
Route list created in files:
  ".\dist\static\assets\scully-routes.json",
  "<local-path>\dist\<my-user-name>\assets\scully-routes.json",
  "<local-path>\src\assets\scully-routes.json"

Route "" rendered into file: ".\dist\static\index.html"

Generating took 13.67 seconds for 1 pages:
  That is 0.08 pages per second,
  or 13675 milliseconds for each page.

  Finding routes in the angular app took 7.94 seconds
  Pulling in route-data took 2 milliseconds
  Rendering the pages took 3.01 seconds



ERROR: The process "2488" not found.
```

#### 💻Your Environment

Windows machine running git bash

**Angular Version:**

9.1.9

## 🔥 Exception or Error

ERROR: The process "2488" not found.

**Comment by SanderElias** [comment] 2020-07-11 04:39
Closing as duplicate of #79

**Closed by SanderElias** 2020-07-11 04:39 UTC
Labels: bug

**Comment by Ferie** [comment] 2020-07-20 04:34
Closed without solution?

In the closed mentioned issue there is no solution...

So the bug persist and you simply do not care?

**Comment by SanderElias** [comment] 2020-07-20 15:35
We do care, but as the bug is _inside_ the c part of NodeJs, and its actually _not_ in the way of anything. (it is just visually disturbing, and _not_ affecting anything in the Scully runtime) There is not so much we can do.
Its not a bug, but a false-positive form the node runtime on windows. 
This is all explained in #79. As there is no update or change there is no use in keeping this issue open.
We are tracking the progress inside the node-repo and will leave an update in #79 when its resolved.
As there is nothing we can do in Scully, there is no use of keeping the issue open.
