### ISSUE TITLE
Got error: connect ECONNREFUSED 127.0.0.1:1864

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#269] opened 2020-02-03 15:08 UTC
### Description

when use tsc -p ./scully/tsconfig.scully.json && node scully\bin\scully.js the httpGetJson generate a console log with this message Got error: connect ECONNREFUSED 127.0.0.1:1864 we need remove in this case because is not important here

#### 💻Your Environment

**Angular Version:**

<pre><code>

</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by jorgeucano** [comment] 2020-02-03 17:11
![image](https://user-images.githubusercontent.com/5982204/73674322-02d4f580-468f-11ea-86eb-84a013bddf4c.png)

**Comment by jorgeucano** [comment] 2020-02-07 13:04
I cant not reproduce!

**Comment by jorgeucano** [comment] 2020-02-07 13:05
If any have this problem, and can reproduced please write here, we are really happy to fix that :D

**Comment by msacket** [comment] 2020-02-07 18:35
I'm not sure if it's related; however, I was getting the `ECONNREFUSED` error across the board until I noticed a `ScullyServer` process from a previous `npm run scully` was still active.  After I quit that process, it started working again.

**Comment by SanderElias** [comment] 2020-02-10 08:00
@jorgeucano having 2 instances running might be related.

**Comment by jorgeucano** [comment] 2020-02-10 13:24
I will check now, thanks @msacket !

**Comment by msacket** [comment] 2020-02-10 14:13
@jorgeucano no problem.  Just as a quick follow up, I'm not sure how the `ScullyServer` from the previous execution stayed running.  When I began having the problem I restarted VSCode and the issue remained... until I noticed and quit the dangling one.

**Comment by msacket** [comment] 2020-02-11 16:43
I figured out that if you throw an uncaught error in a plugin... the `ScullyServer` will continue running even  though the `npm run scully` exits.  At that point, the `ERR_CONNECTION_REFUSED` occurs until `ScullyServer` is manually quit.

**Comment by billiaug** [comment] 2020-02-23 11:40
I've just run the getting started tutorial and this same error showed.
This might be the way to reproduce?
` ~/projects/my-scully-app
±  |master U:6 ?:5 🔥 | → npm run scully

> my-scully-app@0.0.0 scully /Users/glenn/Projects/my-scully-app
> scully

 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.
Pull in data to create additional routes.
Finding files in folder "/Users/glenn/Projects/my-scully-app/blog"
Route list created in files:
  "/Users/glenn/Projects/my-scully-app/src/assets/scully-routes.json",
  "/Users/glenn/Projects/my-scully-app/dist/static/assets/scully-routes.json",
  "/Users/glenn/Projects/my-scully-app/dist/my-scully-app/assets/scully-routes.json"

Puppeteer error while rendering "" Error: net::ERR_CONNECTION_REFUSED at http://localhost:1864
Puppeteer error while rendering "/blog/2020-02-23-blog" Error: net::ERR_CONNECTION_REFUSED at http://localhost:1864/blog/2020-02-23-blog
Puppeteer error while rendering "" Error: net::ERR_CONNECTION_REFUSED at http://localhost:1864
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! my-scully-app@0.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the my-scully-app@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/glenn/.npm/_logs/2020-02-23T11_39_04_158Z-debug.log
`

**Comment by billiaug** [comment] 2020-02-23 11:51
I've added this to a repo: https://github.com/billiaug/scully-gettingstarted
Just clone, $npm i, $ng build, $npm run scully => error. 

Versions:
Angular: 9.0.2
Angular CLI: 9.0.3
NPM:6.13.6
Node:v12.10.0

**Comment by geromegrignon** [comment] 2020-02-23 12:55
I can't reproduce your problem using your repo and following the steps (npm install, ng build, npm run scully) : 

Here is the successful output doing `npm run scully` on your project : 

```
> my-scully-app@0.0.0 scully C:\Workspace\Oneshots\scully-gettingstarted
> scully

 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.
Pull in data to create additional routes.
Finding files in folder "C:\Workspace\Oneshots\scully-gettingstarted\blog"
Route list created in files:
  "C:\Workspace\Oneshots\scully-gettingstarted\src\assets\scully-routes.json",
  "C:\Workspace\Oneshots\scully-gettingstarted\dist\static\assets\scully-routes.json",
  "C:\Workspace\Oneshots\scully-gettingstarted\dist\my-scully-app\assets\scully-routes.json"

Route "" rendered into file: "C:\Workspace\Oneshots\scully-gettingstarted\dist\static\index.html"
Route "/blog/2020-02-23-blog" rendered into file: "C:\Workspace\Oneshots\scully-gettingstarted\dist\static\blog\2020-02-23-blog\index.html"  
send reload

Generating took 5.95 seconds for 2 pages:
  That is 0.34 pages per second,
  or 2978 milliseconds for each page.

  Finding routes in the angular app took 3.2 seconds
  Pulling in route-data took 9 milliseconds
  Rendering the pages took 939 milliseconds
```

**Comment by geromegrignon** [comment] 2020-02-23 15:32
Also getting the error on a PR (#319) : 

```
Run node ./dist/scully/scully --tds --host='0.0.0.0'
 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.
Pull in data to create additional routes.
Finding files in folder "/home/runner/work/scully/scully/blog"
The file /home/runner/work/scully/scully/blog/page-5.md is empty, scully will ignore.
The file /home/runner/work/scully/scully/blog/testing-empty.md is empty, scully will ignore.
Route list created in files:
  "/home/runner/work/scully/scully/projects/sampleBlog/src/assets/scully-routes.json",
  "/home/runner/work/scully/scully/dist/static/assets/scully-routes.json",
  "/home/runner/work/scully/scully/dist/sampleBlog/assets/scully-routes.json"

Puppeteer error while rendering "/about" Error: net::ERR_CONNECTION_REFUSED at http://0.0.0.0:1864/about
Puppeteer error while rendering "/home/all" Error: net::ERR_CONNECTION_REFUSED at http://0.0.0.0:1864/home/all
Puppeteer error while rendering "/about" Error: net::ERR_CONNECTION_REFUSED at http://0.0.0.0:1864/about
##[error]Process completed with exit code 15.
```

**Comment by billiaug** [comment] 2020-02-23 18:57
So I've found out that running `$npm scrully serve` only stays up for about 10 seconds.
During that time the serve command works fine and I see my app running.
But then it get's killed/shutdown by itself. I assume that's also the reason why the export is not working.

**Comment by SanderElias** [comment] 2020-02-27 16:16
I have updated the server in a couple of my last PR's and this problem should be solved by now.
I'm going to close it, but if any of you still have this issue after our next NPM release, please open a new issue. (or ping us to reopen this one)

**Closed by SanderElias** 2020-02-27 16:16 UTC
Labels: WIP, bug
