### ISSUE TITLE
scully error 8500 on: npm run scully -- --scanRoutes

### ISSUE THREAD

**Issue by denversaka** [scullyio/scully#1138] opened 2020-11-21 08:43 UTC
## 🐞 Bug report
⠼ Erreur�: le processus "8500" est introuvable

### Description

source code to reproduce:
git clone https://jargon330@bitbucket.org/jargon330/blog-iner-code.git

#### 🔬 Minimal Reproduction
ng add @scullyio/init
ng build --prod

npm run scully
`
npm run scully

> blog-iner-code@0.0.0 scully C:\_work\_dev-perso\blog-iner-code
> scully

using plugins from folder "./scully"
 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.
⠸ warming up
----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
Route list created in files:
  ".\src\assets\scully-routes.json",
  "C:\_work\_dev-perso\blog-iner-code\dist\static\assets\scully-routes.json",
  "C:\_work\_dev-perso\blog-iner-code\dist\blog-iner-code\assets\scully-routes.json"

Route "/tutos" rendered into file: ".\dist\static\tutos\index.html"
Route "/home" rendered into file: ".\dist\static\home\index.html"
Route "" rendered into file: ".\dist\static\index.html"
Route "/angular" rendered into file: ".\dist\static\angular\index.html"
Route "/api-platform" rendered into file: ".\dist\static\api-platform\index.html"
Route "/poo-php" rendered into file: ".\dist\static\poo-php\index.html"
Route "/symfony-lib" rendered into file: ".\dist\static\symfony-lib\index.html"
Route "/symfony-listener" rendered into file: ".\dist\static\symfony-listener\index.html"
Route "/display-products" rendered into file: ".\dist\static\display-products\index.html"
Route "/mes-sites" rendered into file: ".\dist\static\mes-sites\index.html"

Generating took 80.28 seconds for 10 pages:
  That is 0.13 pages per second,
  or 8029 milliseconds for each page.

  Finding routes in the angular app took 7 milliseconds
  Pulling in route-data took 3 milliseconds
  Rendering the pages took 79.56 seconds

**⠴ Erreur�: le processus "8680" est introuvable.**
`

`
npm run scully -- --scanRoutes

> blog-iner-code@0.0.0 scully C:\_work\_dev-perso\blog-iner-code
> scully "--scanRoutes"

using plugins from folder "./scully"
 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
Route list created in files:
  ".\src\assets\scully-routes.json",
  "C:\_work\_dev-perso\blog-iner-code\dist\static\assets\scully-routes.json",
  "C:\_work\_dev-perso\blog-iner-code\dist\blog-iner-code\assets\scully-routes.json"

Route "/tutos" rendered into file: ".\dist\static\tutos\index.html"
Route "/angular" rendered into file: ".\dist\static\angular\index.html"
Route "/home" rendered into file: ".\dist\static\home\index.html"
Route "" rendered into file: ".\dist\static\index.html"
Route "/symfony-lib" rendered into file: ".\dist\static\symfony-lib\index.html"
Route "/poo-php" rendered into file: ".\dist\static\poo-php\index.html"
Route "/api-platform" rendered into file: ".\dist\static\api-platform\index.html"
Route "/symfony-listener" rendered into file: ".\dist\static\symfony-listener\index.html"
Route "/display-products" rendered into file: ".\dist\static\display-products\index.html"
Route "/mes-sites" rendered into file: ".\dist\static\mes-sites\index.html"

Generating took 84.27 seconds for 10 pages:
  That is 0.12 pages per second,
  or 8428 milliseconds for each page.

  Finding routes in the angular app took 3.98 seconds
  Pulling in route-data took 1 milliseconds
  Rendering the pages took 79.56 seconds

**⠼ Erreur�: le processus "8500" est introuvable.**
`

npm run scully:serve

#### 💻Your Environment
windows 10

**Angular Version:**

<pre><code>

Angular CLI: 11.0.2
Node: 12.13.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.0
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.0
@nguniversal/express-engine     11.0.0
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",

</code></pre>

## 🔥 Exception or Error

<pre><code>

in navigator
`
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at new ki (main.fb1945dc5a41b09785bb.js:1)
    at Ai.resolveComponentFactory (main.fb1945dc5a41b09785bb.js:1)
    at n.activateWith (main.fb1945dc5a41b09785bb.js:1)
    at Ed.activateRoutes (main.fb1945dc5a41b09785bb.js:1)
    at main.fb1945dc5a41b09785bb.js:1
    at Array.forEach (<anonymous>)
    at Ed.activateChildRoutes (main.fb1945dc5a41b09785bb.js:1)
    at Ed.activate (main.fb1945dc5a41b09785bb.js:1)
    at k.project (main.fb1945dc5a41b09785bb.js:1)
    at k._next (main.fb1945dc5a41b09785bb.js:1)
    at Z (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at Z (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at polyfills.8d7eafc5a2414dc5ec29.js:1
    at l.invokeTask (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at e.onInvokeTask (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at l.invokeTask (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at Object.onInvokeTask (main.fb1945dc5a41b09785bb.js:1)
    at l.invokeTask (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at i.runTask (polyfills.8d7eafc5a2414dc5ec29.js:1)
    at m (polyfills.8d7eafc5a2414dc5ec29.js:1)
`

</code></pre>

**Comment by SanderElias** [comment] 2020-11-22 12:20
Duplicate of #79

**Closed by SanderElias** 2020-11-22 12:20 UTC
Labels: bug
