### ISSUE TITLE
Cannot upgrade to Angular 13.0 when using scully.

### ISSUE THREAD

**Issue by Sapython** [scullyio/scully#1556] opened 2022-03-09 10:40 UTC
## 🐞 Bug report
```
ng update @angular/cdk @angular/cli @angular/core @angular/material @angular-eslint/schematics
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 13.2.5 to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 56 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^13.0.0", would install "14.0.0-next.5")
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/service-worker" (requires "^13.0.0", would install "14.0.0-next.5")
                  Package "@angular/animations" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@angular/common" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@scullyio/ng-lib" has an incompatible peer dependency to "@angular/common" (requires ">12.0.0 || <13.0.0" (extended), would install "14.0.0-next.5").
                  Package "@angular/animations" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5" (extended), would install "13.2.5").
                  Package "@angular/forms" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@angular/platform-browser" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@angular/platform-browser-dynamic" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@scullyio/ng-lib" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires ">12.0.0 || <13.0.0" (extended), would install "14.0.0-next.5").
                  Package "@angular/platform-server" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@scullyio/platform-server" has an incompatible peer dependency to "@angular/platform-server" (requires ">12.0.0 || <13.0.0" (extended), would install "14.0.0-next.5").
                  Package "@angular/router" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
                  Package "@scullyio/ng-lib" has an incompatible peer dependency to "@angular/router" (requires ">12.0.0 || <13.0.0" (extended), would install "14.0.0-next.5").
                  Package "@angular/service-worker" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.5", would install "13.2.5")
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\sapta\AppData\Local\Temp\ng-rI1aAr\angular-errors.log" for further details.
```
### Description
Not able to upgrade to angular v13 because Scully has a peer dependency that requires angular version less than 13.0.0

#### 🔬 Minimal Reproduction
Create a project with angular CLI v13
And add Scully to the project

 OR

Create a project in angular version 12
And upgrade to version 13

#### 💻Your Environment
Windows 11
Npm Version: 6.14.16
Node Version: v14.19.0

**Angular Version:**
v12.2.6

<pre><code>Angular CLI: 12.2.16
Node: 14.19.0
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 12.2.16
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.16
@angular-devkit/build-angular   12.2.16
@angular-devkit/core            12.2.16
@angular-devkit/schematics      12.2.16
@angular/cdk                    12.2.13
@angular/fire                   7.2.1
@angular/material               12.2.13
@schematics/angular             12.2.16
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Scully Version:**

<pre><code>"@scullyio/init": "^2.1.21",
"@scullyio/ng-lib": "^2.1.21",
"@scullyio/platform-server": "^2.1.21",
"@scullyio/scully": "^2.1.21",
"@scullyio/scully-plugin-puppeteer": "^2.1.21",
</code></pre>

## 🔥 Exception or Error

<pre><code>× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
See "C:\Users\sapta\AppData\Local\Temp\ng-rI1aAr\angular-errors.log" for further details.
</code></pre>

**Comment by SanderElias** [comment] 2022-03-09 16:44
I will copy-paste my answer from #1546:
This is not a bug. The current version doesn't officially support Angular 13.
There are 2 ways around this.
1. Use the `@next` version.
2. use the npm `--legacy-peer-deps` option

Also. we need node 14 or above, and a current NPM version. (8.3 or higher)

For both, you might want to manually install the dependencies:
```bash
# install the most current NPM version
npm i -g npm
# get rid of old possible conflicting packages
rm -fr node_modules
# remove the lock-file because it possible holds conflicting packages
rm package-lock.json
# Use npm with legacy deps, as this solves problems with 4rth party scripts
npm i --legacy-peer-deps 
# Install all the needed Scully packages in the correct order. 
npm i @scullyio/scully@next @scullyio/scully-plugin-puppeteer@next @scullyio/ng-lib@next @scullyio/init@next --legacy-peer-deps
# run the Scully `ng add` schematic manually
npx ng g @scullyio/init:ng-add --renderer puppeteer
```

If you prefer, you can replace the `@next` part with `@2` (that's the latest 2, you can be more specific if you like), and keep on running the current version instead.

I'm closing this for now, as I don't think there is anything left we can do. If you have additional questions, we can keep discussing those here, and if needed, I'll re-open the issue.

Official Angular 13 support will come when we release version 3 (I hope soon). The version is available for testing as noted above.

**Closed by SanderElias** 2022-03-09 16:44 UTC
Labels: question

**Comment by edezekiel** [comment] 2022-03-17 00:57
I've found that adding a .npmrc file to an Angular v13 project with `legacy-peer-deps=true` _before_ running `ng add @scullyio/init` is another way to successfully install scully.

I took this approach from a recommendation to similar issue faced by ngrx: https://github.com/ngrx/platform/issues/2830#issuecomment-1047807929

**Comment by salisshuaibu11** [comment] 2022-05-31 22:52
> I've found that adding a .npmrc file to an Angular v13 project with `legacy-peer-deps=true` _before_ running `ng add @scullyio/init` is another way to successfully install scully.
> 
> I took this approach from a recommendation to similar issue faced by ngrx: [ngrx/platform#2830 (comment)](https://github.com/ngrx/platform/issues/2830#issuecomment-1047807929)

It works for me also.
