### ISSUE TITLE
Following the docs for a starter app, getting "The process 8472 not found"

### ISSUE THREAD

**Issue by franklin626** [scullyio/scully#850] opened 2020-08-15 22:14 UTC
I followed the docs to create a starter Scully app. Upon `npm run scully` after `ng build`, I get: 

```
Route list created in files:
  ".\dist\static\assets\scully-routes.json",
  "C:\Users\jerom\blog\scully-blog\dist\scully-blog\assets\scully-routes.json",
  "C:\Users\jerom\blog\scully-blog\src\assets\scully-routes.json"

Route "/" rendered into file: ".\dist\static\index.html"

Generating took 30.28 seconds for 1 pages:
  That is 0.04 pages per second,
  or 30289 milliseconds for each page.
  
  Finding routes in the angular app took 3.4 seconds
  Pulling in route-data took 2 milliseconds
  Rendering the pages took 25.72 seconds

**⠋ ERROR: The process "8472" not found.**
```

package.json:
```
{
  "name": "scully-blog",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.9",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
    "@angular/router": "~10.0.9",
    "@scullyio/init": "^1.0.0-beta.0",
    "@scullyio/ng-lib": "^1.0.0-beta.0",
    "@scullyio/scully": "^1.0.0-beta.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.6",
    "@angular/cli": "~10.0.6",
    "@angular/compiler-cli": "~10.0.9",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}
```

**Comment by SanderElias** [comment] 2020-08-17 09:43
closing as a duplicate of #732 and #79

**Closed by SanderElias** 2020-08-17 09:43 UTC
Labels: bug
