### ISSUE TITLE
Scully dynamic route generation issue.

### ISSUE THREAD

**Issue by adityakoushikr11** [scullyio/scully#912] opened 2020-09-08 12:12 UTC
### Description
Could not fetch data for route "/add-ons/:pageUrl"
#### 💻Your Environment

**Angular Version:**

<pre><code>

</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by adityakoushikr11** [comment] 2020-09-08 12:53
How to fix this issue.  i am making an https api call to fetch data from server

**Comment by geromegrignon** [comment] 2020-09-08 13:49
Please consider filling in the issue template with : 
- minimal reproduction
- your environment
- complete error stack trace

It will speed up the maintainers response to your issue.

**Comment by SanderElias** [comment] 2020-09-09 09:57
@adityakoushikr11 There is nothing in your issue we can act upon.
There is no way to guide you, as we simply don't know what you are trying to do.
A wild guess would be, there is a mistake in the endpoint URL.

**Comment by SanderElias** [comment] 2020-09-10 04:17
Closing due to a lack of actionable context

**Closed by SanderElias** 2020-09-10 04:17 UTC

**Comment by Paldom** [comment] 2022-08-02 20:01
Hi,
for me, addig proper JSON headers at backend, like
`res.set('Content-Type', 'application/json');`
solved this issue. If anyone still struggles with this one.
