### ISSUE TITLE
Scully init issue with angular 13

### ISSUE THREAD

**Issue by 3gwebtrain** [scullyio/scully#1481] opened 2021-11-26 05:41 UTC
I am trying to install scully with angular version 13. but getting errors from scully. how to handle this?
here is the errors:

`warning @scullyio/init > guess-parser > @wessberg/ts-evaluator@0.0.27: this package has been renamed to ts-evaluator. Please install ts-evaluator instead
warning @scullyio/init > schematics-utilities > @schematics/update > ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
warning " > bootstrap@5.1.3" has unmet peer dependency "@popperjs/core@^2.10.2".
warning " > @scullyio/init@2.0.5" has unmet peer dependency "guess-parser@^0.4.22".
warning "@scullyio/init > @angular/router@12.2.6" has incorrect peer dependency "@angular/platform-browser@12.2.6".
warning "@scullyio/init > @angular/platform-server@12.2.13" has incorrect peer dependency "@angular/animations@12.2.13".
warning "@scullyio/init > @angular/platform-server@12.2.13" has incorrect peer dependency "@angular/common@12.2.13".
warning "@scullyio/init > @angular/platform-server@12.2.13" has incorrect peer dependency "@angular/compiler@12.2.13".
warning "@scullyio/init > @angular/platform-server@12.2.13" has incorrect peer dependency "@angular/core@12.2.13".
warning "@scullyio/init > @angular/platform-server@12.2.13" has incorrect peer dependency "@angular/platform-browser@12.2.13".
warning "@scullyio/init > @angular/platform-server@12.2.13" has incorrect peer dependency "@angular/platform-browser-dynamic@12.2.13".
× Package install failed, see above.
`
my package.json:

`{
  "name": "my-blog",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "bootstrap": "^5.1.3",
    "rxjs": "~7.4.0",
    "ts-evaluator": "^0.1.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.3",
    "@angular/cli": "~13.0.3",
    "@angular/compiler-cli": "~13.0.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.4.3"
  }
}
`

**Comment by SanderElias** [comment] 2021-11-26 08:14
@3gwebtrain I can not reproduce your issue, can you give me some more context when this happens for you?
![image](https://user-images.githubusercontent.com/1249083/143548459-41823570-4769-4b9a-862d-1098b897cf59.png)

**Comment by 3gwebtrain** [comment] 2021-11-26 14:28
Is it required to use `npx` instead of `yarn` -?

**Comment by SanderElias** [comment] 2021-11-27 14:24
@3gwebtrain Not as far as we know.

**Comment by SanderElias** [comment] 2021-12-04 04:38
Closing, because we can't reproduce. If there is more info available, I'm more as happy to reopen the issue

**Closed by SanderElias** 2021-12-04 04:38 UTC
Labels: can't reproduce
