### ISSUE TITLE
routes.json get all the images

### ISSUE THREAD

**Issue by stevermeister** [scullyio/scully#653] opened 2020-06-24 11:47 UTC
## 🐞 Bug report

Scully already knows how to ignore all files except *.md, but it still adds all these exceptions to compiled routes.json file.

**Comment by SanderElias** [comment] 2020-07-02 09:52
I looked at this, and when I add more images to the scully-blog test suite, those are just ignored

**Comment by SanderElias** [comment] 2020-07-02 14:46
Closing this, as I can't reproduce. When you can a file-plugin that handles image types, this will make Scully try to process them

**Closed by SanderElias** 2020-07-02 14:46 UTC
Labels: need more info, need repo example
