### ISSUE TITLE
Docs don't make it clear on how to render the blog post

### ISSUE THREAD

**Issue by ajsaraujo** [scullyio/scully#1449] opened 2021-10-26 01:46 UTC
## 🗄️ Docs report

In the "Create a blog" guide, the docs go over:

- Generating the blog setup;
- Using blog data in the Angular template (a.k.a get the list of posts)
- Generating new blog posts.

However, it does not explain how to actually render the blog post itself.

Ok, this is done automatically, but it's not clear for the user how he's supposed to see his blog post live. It would be nice if, after generating the config, the doc told us something like _"Cool, now your post is live at http://localhost:1668/blog/test-post"_

**Comment by SanderElias** [comment] 2021-11-03 03:51
Closing as a duplicate of #1420.
Please focus the discussion there. 
I would love to see a docs PR that would fix this issue.

**Closed by SanderElias** 2021-11-03 03:51 UTC
Labels: documentation
