### ISSUE TITLE
Scully doesn't build with Angular Dynamic platformBrowserDynamic 

### ISSUE THREAD

**Issue by norato** [scullyio/scully#1430] opened 2021-09-17 15:09 UTC
### Description
The generated HTML from Scully is the same index.html from app dist. Investigating this, if I remove the dynamic value to set a provider inside the **platformBrowserDynamic** the HTML is created as expected.
The value from the provider is fetched and needs to be defined before the app initialization. The application runs as expected the Angular build, but the Scully not

#### 🔬 Minimal Reproduction
Inside the main.ts, add a provider that depends on a request to get the values.

```ts
const configXhr = new XMLHttpRequest();
configXhr.open('GET', configPath);
configXhr.send();
configXhr.onreadystatechange = function () {
  if (this.status === 200 && this.readyState === 4) {
    const config = JSON.parse(configXhr.responseText);
    if (environment.production) {
      enableProdMode();
    }
    platformBrowserDynamic([
      {
        provide: GLOBAL_CONFIG,
        useValue: config,
      },
    ])
      .bootstrapModule(AppModule)
      .catch((err) => console.error(err));
  }
};
```

#### 💻Your Environment

**Angular Version:**

<pre><code>

11.6.0
</code></pre>

**Scully Version:**

<pre><code>

 "dependencies": {
    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0"
 },
 "devDependencies": {
    "@nrwl/workspace": "11.6.0",
    "@scullyio/scully-plugin-base-href-rewrite": "^1.1.1",
 }

</code></pre>

## 🔥 Exception or Error

<pre><code>

Warning: ./apps/main/src/main.ts 40:15-46
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/norato/projects/my-app/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/norato/projects/my-app/node_modules/webpack/lib/Compilation.js:1454:24)
    at /Users/norato/projects/my-app/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/Users/norato/projects/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at eval (eval at create (/Users/norato/projects/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:57:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./apps/main/src/main.ts
</code></pre>

**Comment by SanderElias** [comment] 2021-09-24 05:57
@norato Can you try with V12 and Scully v2?

**Comment by SanderElias** [comment] 2022-03-25 07:48
Closing due to lack of actionable context. If this still is the case, can you provide a minimal repo that reproduces this behavior? We will gladly reopen and work out the issue

**Closed by SanderElias** 2022-03-25 07:48 UTC
Labels: bug
