### ISSUE TITLE
error when clicked on markdown generated link 

### ISSUE THREAD

**Issue by xmlking** [scullyio/scully#121] opened 2019-12-31 00:26 UTC
# 🐞 Bug report

### Description
I have a link (/home/blog)  in my markdown ` blog-post` to `blog-post-lust-view` as shown below 
When I click the link, `<a href="/home/blog">site-map</a>` I am getting following error 

```
libs-home-src-lib-home-module-es2015.js:902 problem during parsing static scully content TypeError: Cannot read property 'split' of undefined
```
Markdown blog
```
---
title: blog 1
description: This is the first demo blog in this sample.
---

# blog 1

## its a wild world after all

Related information [blog-2](/home/blog/blog-2)

[site-map](/home/blog)
```
## 🔬 Minimal Reproduction
![image](https://user-images.githubusercontent.com/627951/71605697-dc67eb80-2b1f-11ea-86f8-e93afab981bf.png)

## 💻Your Environment 
**Angular Version:**
<pre><code>

</code></pre>

**Scully Version:**
<pre><code>

</code></pre>
## 🔥 Exception or Error
I think the error is caused at
<pre><code>
https://github.com/scullyio/scully/blob/master/projects/scullyio/ng-lib/src/lib/scully-content/scully-content.component.ts#L75
</code></pre>

**Comment by SanderElias** [comment] 2019-12-31 10:02
Can you provide a repo that reproduces this? I seem unable to reproduce this scenario

**Comment by xmlking** [comment] 2020-01-01 09:08
https://github.com/xmlking/yeti

**Comment by aaronfrost** [comment] 2020-01-02 05:12
I will look at this tomorrow.

**Comment by SanderElias** [comment] 2020-01-03 09:40
@xmlking 
![yeti-demo](https://user-images.githubusercontent.com/1249083/71716510-48df3500-2e15-11ea-8809-814c325e08b7.gif)
It works for me. I'm not sure what happens on your system?

**Comment by xmlking** [comment] 2020-01-04 05:36
Click site-map and see console logs

**Comment by SanderElias** [comment] 2020-01-05 11:26
Ok, now I'm seeing the error. 
It does not make sense, the error is on a page that doesn't (or at least should not) contain the `scully-content` component. yet the error is raised from there. 
Can you provide more pointers on how this could happen?

**Comment by SanderElias** [comment] 2020-01-05 12:33
@xmlking I found the root of the issue. Building a fix right now.

**Comment by xmlking** [comment] 2020-01-09 22:00
I still get error after going to blog page `https://ngx-starter-kit.firebaseapp.com/home/blog/blog-4` 
then clicking on `YETI`  on the header 
![image](https://user-images.githubusercontent.com/627951/72108286-19826980-32e8-11ea-9762-a440946e4de9.png)


![image](https://user-images.githubusercontent.com/627951/72108367-49317180-32e8-11ea-90b8-7e9878647d1a.png)

**Comment by SanderElias** [comment] 2020-01-10 08:07
Are you sure you updated to the latest `@scullyio/ng-lib` ?

**Comment by xmlking** [comment] 2020-01-11 18:06
yes I am using `0.0.8`.  
how to reproduce.:
clone https://github.com/xmlking/yeti
```
yarn run scully:all
or 
npx run scully:all
```

clicking links in blog posts works fine. even the `site-map` , but from block post, if you click `YETI` home link on the left, then you will see this error.

**Comment by xmlking** [comment] 2020-01-11 18:15
I also notices other problem, maybe related....
in the same repo run only angular `ng serve`
```
ng serve
```
then click blog post and then click , home. you will see `scullyio-ng-lib.js:402 problem during loading static scully content ` error

I dont have any `scullyio` in home(landing) page. why I do see this error when clicking `/home` linkk?

**Comment by SanderElias** [comment] 2020-01-12 06:34
@xmlking That would be the same bug/reason. It looks like it regressed back somehow. going to check.

**Comment by SanderElias** [comment] 2020-01-12 17:14
I looked into it. It isn't exactly the same bug, but closely related. Looking for a fix. Might take a day or 2.

**Comment by SanderElias** [comment] 2020-01-14 05:58
I addressed this issue. I don't recall the exact PR, but it will be fixed when we drop the new version.
You can expect this to be later today. closing this now.
When you find any new regressions, please open a new issue, and refer this one.

**Closed by SanderElias** 2020-01-14 05:58 UTC
Labels: waiting for new publish
