### ISSUE TITLE
Problem with scully when building project with --base-href flag

### ISSUE THREAD

**Issue by harounchebbi** [scullyio/scully#1088] opened 2020-10-13 14:09 UTC
## 🐞 Bug report
After building my angular app with --base-href flag, scully content is not rendered in the browser. 

#### 🔬 Minimal Reproduction

ng build --prod --base-href /project-name/ && npm run scully
scully content not found when navigating to the route in question.
This only happens when specifying --base-href which I obviously need to deploy the static site. 

#### 💻Your Environment

**Angular Version:** 

<pre><code>
Angular CLI: 9.0.6
Node: 12.13.0
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "1.0.1",
"@scullyio/ng-lib": "1.0.0",
"@scullyio/scully": "1.0.2",
</code></pre>

## 🔥 Exception or Error

<pre><code>

Scully could not find the <.scully-content>. tag in this page.
This error can happen when you forgot to put the mandatory "scully-content" in the component that is rendering this page?

Or when the tag is not shown on page load. Did you put it inside an `*ngIf`?

</code></pre>

**Comment by SanderElias** [comment] 2020-10-15 07:37
Duplicate of #699 
This is a direct result of what base-href does.
If you need a base-href, use our base-href plugin to set it.
You can use the angular CLI for this, but then you need to move your distribution files into the correct folder structure before Scully can render it.

**Closed by SanderElias** 2020-10-15 07:37 UTC
Labels: question

**Comment by harounchebbi** [comment] 2020-10-16 09:57
Thank you @SanderElias . It worked with the plugin 😃
