### ISSUE TITLE
Puppeteer render issue.  

### ISSUE THREAD

**Issue by adityakoushikr11** [scullyio/scully#1122] opened 2020-11-13 09:57 UTC
## 🐞 Bug report
Puppeteer render issue.
### Description
Scully build works fine in my local computer, when we are trying to run scully build through Gitlab CI/CD pipeline, i get the following error
The ___Scully_system_plugins_Alter_at_own_RISK___ plugin "puppeteerRender has thrown the below error,
              while trying to render route "unknown"
              Scully will exit
Error: Protocol error: Connection closed. Most likely the page has been closed.
#### 🔬 Minimal Reproduction
First i run ng build --prod --configuration=production and then i run npm run scully, this process is throwing error in gitlab CI/CD pipeline.
#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.0.1
Node: 12.18.3
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/http                     7.2.16
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "1.0.1",
    "@scullyio/ng-lib": "1.0.0",
    "@scullyio/scully": "1.0.3",

</code></pre>

## 🔥 Exception or Error

<pre><code>
The ___Scully_system_plugins_Alter_at_own_RISK___ plugin "puppeteerRender has thrown the below error,
              while trying to render route "unknown"
              Scully will exit
Error: Protocol error: Connection closed. Most likely the page has been closed.

</code></pre>

**Comment by adityakoushikr11** [comment] 2020-11-13 09:57
![Web capture_13-11-2020_152024_gitlab com](https://user-images.githubusercontent.com/33486608/99059550-c2fb5100-25c4-11eb-88ec-c65bfe48dd7d.jpeg)

**Comment by SanderElias** [comment] 2020-11-13 10:33
@adityakoushikr11 Can you try Scully 1.0.4? There was something similar to this that was solved.
Aside from that, we have a cmd-line option that is there so Scully will progress, without exiting when a route fails. (`--pluginsError=false`).  Then you can access what route is missing, and isolate the problem a bit more.

**Comment by adityakoushikr11** [comment] 2020-11-13 10:36
@SanderElias sure. I will get back to you in sometime.

**Comment by adityakoushikr11** [comment] 2020-11-13 11:54
@SanderElias i am getting same error even after adding update scully to 1.0.4 and executing npm run scully --pluginsError=false

**Comment by SanderElias** [comment] 2020-11-13 13:17
I have looked at your logs again. It seems an issue with Puppeteer. 
Can you try lowering the config options `maxRenderThreads: 32` to half of the threads you have available on your system?

**Comment by adityakoushikr11** [comment] 2020-11-16 05:26
@SanderElias  can u tell me where to set maxRenderThreads: 32

**Comment by adityakoushikr11** [comment] 2020-11-16 05:51
@SanderElias i am getting the following error
`Puppeteer error while rendering "/videos/flutter-saas-app-dashboard-installation-set-up-" TimeoutError: Navigation timeout of 30000 ms exceeded  we will retry rendering this page up to 3 times.
Puppeteer error while rendering "/videos/node-js-clothing-dashboard-installation-set-up-" TimeoutError: Navigation timeout of 30000 ms exceeded  we will retry rendering this page up to 3 times.
Puppeteer error while rendering "/videos/multi-restaurant-ionic-app-dashboard-features" TimeoutError: Navigation timeout of 30000 ms exceeded  we will retry rendering this page up to 3 times.`

**Comment by SanderElias** [comment] 2020-11-16 15:04
That seems like a failure of a single page (or actually 2 different ones)
Is there anything special in those?

**Comment by SanderElias** [comment] 2020-11-18 14:31
As there is no current actionable activity in here, I'm closing this for now.
If there is anything new, We are more than willing to reopen the issue!

**Closed by SanderElias** 2020-11-18 14:31 UTC
Labels: bug

**Comment by aaronfrost** [comment] 2020-11-19 01:30
We need to make sure we get this solved. This would be very frustrating,
and I'm sure others are seeing it too.

**Comment by jsanta** [comment] 2020-12-09 14:12
Same problem here. Tried deleting one by one  the extraRoutes on my scully.config.ts file with no success.

```
 The ___Scully_system_plugins_Alter_at_own_RISK___ plugin "puppeteerRender has thrown the below error,
              while trying to render route "unknown"
              Scully will exit
Error: Protocol error: Connection closed. Most likely the page has been closed.
⠴ Rendering Routes: 9/10(node:57019) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
⠦ Rendering Routes: 9/10npm ERR! code ELIFECYCLE
```

No useful information for debugging, at least on this level. The sad  part for me is that this worked a few weeks ago and the only change in my code has been adding a new route, doing nothing different from the other routes in my app.

**Comment by SanderElias** [comment] 2020-12-09 16:31
@jsanta can you try again with Scully 1.0.8? (`npm i @scullyio/scully` will do)
I did some changes that might be of influence here. If that doesn't help, ping me, and I will get you a special version so we can debug this a bit more.  This is an error that should be impossible, but I will go over the code one more time to see if I can spot anything that provides any clue

**Comment by jsanta** [comment] 2020-12-09 18:37
> @jsanta can you try again with Scully 1.0.8? (`npm i @scullyio/scully` will do)
> I did some changes that might be of influence here. If that doesn't help, ping me, and I will get you a special version so we can debug this a bit more. This is an error that should be impossible, but I will go over the code one more time to see if I can spot anything that provides any clue

HI thanks for your answer.
Updated, and still the same issue. Trying to find the unknown route, but don't even know where it appeared from.
Also tried  deleting node_modules and just made everything explode....

**Comment by jsanta** [comment] 2020-12-09 20:56
OK some findings:
* Had to install some packages by hand. Somehow I skipped them from my initial npm install run, so they weren't on the package.json . Explosions solved.
* Trying to run scully:serve script showed that port 1668 was taken. Perhaps an old scully failed run... Killed the process and the same error.
* Adjusted some weird redirections on  one of my routes, no results.
* Changed the scully script in my package.json to ``"scully --prod --showGuessError --showBrowser --pluginsError=false --logSeverity=normal --serverTimeout 30000"`` . At least the job finishes the rendering of the routes it can do. The error stays the same.

**Comment by jsanta** [comment] 2021-01-03 13:32
Hi. I know this issue is closed, but I have more accidental findings. I was debugging the app and commented a component that opens a modal with an embedded Youtube video iframe. No puppeteer errors regarding an unknown route. Tried uncommenting and the error appeared again. So the solution was something mentioned on https://github.com/scullyio/scully/issues/801 

On the `scully.config.ts` file added an extra parameter to puppeteerLaunchOptions args array: 
`"--user-agent='Scully Navigator'"`

and conditioned the modal to show only if the  userAgent does not match this fake  userAgent. Something like:
```
    const userAgent: string = window.navigator.userAgent;
    this.showModal = (userAgent === 'Scully Navigator') ? false : true;
```

Works as expected.

I suppose that this is happening due to something related with the iframe, and not the modal itself. I have another internal page that  includes an iframe, but renders it on a different way, and it was rendered correctly by  Scully, and it also happens with another  page that  opens a modal, with the only difference that this modal does not have any iframes inside. So it _might be_ an iframe issue.

**Comment by SanderElias** [comment] 2021-01-04 06:31
@jsanta We do expose a globally available variable that you can use, as well as the `isScullyRunning()` function to handle those kinds of things. Although if the root cause is _inside_ an iframe, that doesn't help you much.  
If you could provide me with a sample that fails, I can take a look, and come up with either a fix or document a workaround like yours.

**Comment by hchings** [comment] 2021-03-25 04:04
Issue solved w/ manual installed and modify relevant files. Still unsure about the root cause but can run Scully now. Thanks.

**Comment by fireflysemantics** [comment] 2021-06-30 06:54
I have had this issue too.  I think it's the type of WIFI that I'm on.  I just ran my build now and it works fine, but when I'm on other public WIFI networks, puppeteer times out.  I wonder if it needs a certain "Handshake" to start up ... and certain public networks are not allowing it.
