### ISSUE TITLE
Scully getting stuck after creating route list on CircleCI

### ISSUE THREAD

**Issue by nhuyvan** [scullyio/scully#927] opened 2020-09-17 04:08 UTC
### Description
I ran Scully locally, and everything worked fine, but when I pushed my changes to CircleCI, Scully wouldn't get past this point as shown in the following image

<img width="1421" alt="Screen Shot 2020-09-16 at 9 00 19 PM" src="https://user-images.githubusercontent.com/13056129/93418645-af9b6600-f85f-11ea-99c5-f644fffb5ab7.png">

#### 🔬 Minimal Reproduction
.circleci/config.yml
```
version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    build:
        docker:
            - image: cimg/node:12.18.2
        steps:
            - checkout
            - run: npm install
            - run: npm run build
            - add_ssh_keys:
                fingerprints:
                    - ...
            - run:
                name: Deploy to gh-pages
                command: |
                    git reset --hard
                    git checkout -b gh-pages origin/gh-pages
                    DEPLOYMENT_NUMBER=$(git log -1 | grep -o 'Deployment [0-9]\+' | sed 's/Deployment //')
                    rm -rf *.html *.css *.js *.txt .ico assets
                    mv dist/static/* .
                    git add .
                    git config user.email ...
                    git config user.name ...
                    git commit -m "[ci skip] Deployment $(($DEPLOYMENT_NUMBER + 1)), $(date  '+%B %d %Y')"
                    git push origin gh-pages
workflow:
    version: 2.1
    build:
        jobs:
            - build
```

package.json
```
{
    "name": ...,
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build --stats-json --prod && npm run scully",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "scully": "scully --serverTimeout=30000",
        "scully:serve": "scully serve"
    },
    "husky": {
        "hooks": {
            "pre-commit": "npm run lint"
        }
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~10.0.6",
        "@angular/cdk": "^10.1.1",
        "@angular/common": "~10.0.6",
        "@angular/compiler": "~10.0.6",
        "@angular/core": "~10.0.6",
        "@angular/forms": "~10.0.6",
        "@angular/material": "^10.1.1",
        "@angular/platform-browser": "~10.0.6",
        "@angular/platform-browser-dynamic": "~10.0.6",
        "@angular/router": "~10.0.6",
        "@scullyio/init": "^1.0.0",
        "@scullyio/ng-lib": "^1.0.0-beta.1",
        "@scullyio/scully": "^1.0.0-beta.5",
        "d3-scale": "^3.2.1",
        "ngx-color": "^6.0.1",
        "rxjs": "~6.6.0",
        "tslib": "^2.0.0",
        "zone.js": "~0.10.2"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.1000.4",
        "@angular/cli": "~10.0.4",
        "@angular/compiler-cli": "~10.0.6",
        "@angular/language-service": "~10.0.6",
        "@types/d3-scale": "^2.2.0",
        "@types/jasmine": "~3.5.11",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "^14.0.27",
        "codelyzer": "^6.0.0",
        "husky": "^4.2.5",
        "jasmine-core": "~3.5.0",
        "jasmine-spec-reporter": "~5.0.0",
        "karma": "~5.0.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage-istanbul-reporter": "~3.0.2",
        "karma-jasmine": "~3.3.0",
        "karma-jasmine-html-reporter": "^1.5.0",
        "protractor": "~7.0.0",
        "scully-plugin-disable-angular": "^5.5.0",
        "scully-plugin-minify-html": "^3.2.0",
        "ts-node": "~8.10.2",
        "tslint": "~6.1.0",
        "typescript": "~3.9.7"
    }
}
```
#### 💻Your Environment

**Angular Version:**

<pre><code>

10.0.6
</code></pre>

**Scully Version:**

<pre><code>

1.0.0
</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by SanderElias** [comment] 2020-09-17 05:39
Duplicate of #924.
We are in the process of adding a proper error message.

**Closed by SanderElias** 2020-09-17 05:39 UTC
Labels: bug
