### ISSUE TITLE
scully-content doesn't work when served over https

### ISSUE THREAD

**Issue by stewwan** [scullyio/scully#131] opened 2020-01-03 00:51 UTC
# 🐞 Bug report

## 🔬 Minimal Reproduction

https://scully-demo.stewan.io/

Then press the link “this is a blog post”

it works on non-secure urls, though.

http://scully-demo.stewan.io/

Here is the repo

https://github.com/stewwan/scully-demo

## 💻Your Environment 
**Angular Version:**
<pre><code>

</code></pre>

**Scully Version:**
<pre><code>

</code></pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by SanderElias** [comment] 2020-01-03 08:10
Hmm, this is strange. Scully-content uses location.href to get the URL. That gives back the `https` link. I have no clue why it is trying to get  the content using `HTTP` 
Scully should be completely agnostic to `HTTP` vs `https`  this needs a bit more investigation.
@aaronfrost Can you take a loo too?

**Comment by SanderElias** [comment] 2020-01-03 08:36
@stewwan Your server does a redirect to the HTTP resource that is causing this issue:
![image](https://user-images.githubusercontent.com/1249083/71713935-167d0a00-2e0c-11ea-812b-8d58cf750236.png)
So your server forwards and returns an HTTP request when asked for an https.
I don't think there is anything here that Scully can do to fix this? Therefore I'm closing this issue. When you think Scully can help somehow to fix this, please open a new issue

**Closed by SanderElias** 2020-01-03 08:36 UTC
Labels: bug

**Comment by stewwan** [comment] 2020-01-03 12:09
But it’s cloudflare + github pages 🤷‍♂️
Any idea on how to fix it?

**Comment by SanderElias** [comment] 2020-01-03 13:34
Nope, sorry, no clue,

**Comment by stewwan** [comment] 2020-01-03 14:15
Why issue is closed then?

**Comment by stewwan** [comment] 2020-01-03 14:16
So that mean if I want to host on github pages or use cloudflare I wont be able to use scully. 👍

**Comment by SanderElias** [comment] 2020-01-03 14:21
I closed it because the cause of the issue is not Scully. It is probably something in the Cloudflare settings. We can't possibly provide a solution for every hosting issue out there. 
Scully works well on https.

**Comment by stewwan** [comment] 2020-01-03 16:06
I'm not doing any redirect even on cloudflare, from where it comes then? 
why this blog post doesn't redirect?
https://stewan.io/en/google/setup-elastic-search-with-kibana-on-google-cloud

I really don't understand this rush on closing issues

but that's fine, have a great day

![Screen Shot 2020-01-03 at 13 02 56](https://user-images.githubusercontent.com/719763/71733988-9e254180-2e29-11ea-94ab-39a6c3213824.png)

**Comment by aaronfrost** [comment] 2020-01-03 20:33
@stewwan I am looking into this. I am sorry that we've frustrated you with closing this issue so fast. I want to spend some additional time looking into this issue for you. If I find something (fingers crossed) we can reopen it. It appears, though, that @SanderElias is probably right that this is some weird host thing that we can't control. 

I will let you know what I find. And THANK YOU for helping us out, and trying out Scully, and submitting issues you run into. I hope that we can help you solve this issue, and help you be successful in your efforts to better understand SSG around Angular.

**Comment by aaronfrost** [comment] 2020-01-03 20:37
@d-koppenhagen have you deployed your stuff and gotten it working? Did you experience this?

**Comment by d-koppenhagen** [comment] 2020-01-03 21:06
Hey, I published my site https://d-koppenhagen.de using scully.
In my case I am using not cloud flare and gh-pages.

A few days ago the site was not redirecting directly to https when calling the url with http but I had no issues with this. I have also no issues with the redirect (using apache as web server).

I assume also it could be a server configuration thing. Have never had a similiar issue with scully so far.

**Comment by d-koppenhagen** [comment] 2020-01-03 21:22
Could it be a problem when the web server is configured in such a way that it will all routes redirect to the root (baseUrl) in order to get the routing handled by the Angular router?
This shouldn't be done in case of using Scully I think as the static routes (directories with index.html) do exist.

**Comment by d-koppenhagen** [comment] 2020-01-03 21:27
So I think the redirect always to `/index.html` as described in the [Angular Docs](https://angular.io/guide/deployment#server-configuration) isn't necessary when using the static sites result of _Scully_ isn't it? Maybe this causes some kind of error? Can you check your Cloudflare config for it?

**Comment by stewwan** [comment] 2020-01-03 22:19
at this point I can see problem isn't with Scully. Thanks y'all
will share if I discover anything.

**Comment by aaronfrost** [comment] 2020-01-03 22:24
@stewwan others will have this same issue. Please share your finding.

**Comment by stewwan** [comment] 2020-01-03 23:28
it works as expected prepending `/index.html`

`https://scully-demo.stewan.io/blog/12-30-2019-blog/index.html`

double checked all cloudflare settings and have found nothing related. there's no redirecting there.

I've tried to change the blog route prepending that `index.html` but also no success. Scully didn't even render the blog post.

still wondering what it could be

**Comment by stewwan** [comment] 2020-01-04 16:15
okay I managed to fix this. I didnt know github pages already supports https out of box so the solution is letting cloudflare be only the dns server by disabling proxy

![Screen Shot 2020-01-04 at 13 11 22](https://user-images.githubusercontent.com/719763/71768320-e27d1400-2ef3-11ea-9ae3-8788e032eb6c.png)

**Comment by BrendanSluke** [comment] 2021-05-24 05:24
I know this is an older (non-Scully) issue but this issue shows up in search results for 'Scully Cloudflare' so I'll leave my findings here.

I was getting a weird obscure result where my Scully Content was rendering to this:
![image](https://user-images.githubusercontent.com/62220614/119300260-14486500-bc26-11eb-9fcc-71722c4fdc36.png)

It renders to `')[1].split('` for some reason (I'm not going to guess why!).

The solution for me right now is to turn my Cloudflare caching 'Development Mode' to ON. It's not a long term solution but it allows my content to render.
![image](https://user-images.githubusercontent.com/62220614/119300384-4954b780-bc26-11eb-8ba3-651f9d029478.png)


I'll try to post a conclusion if I can get it working without removing Cloudflare's caching feature.

**Comment by SanderElias** [comment] 2021-05-24 07:07
@BrendanSluke I suspect there is some HTML modification going on that breaks The way Scully injects the comments it needs.
We had the same exact issue with an HTML minifier. 
You might need to do a setting so that the script we inline in the pages does opt out of "optimization". You opt out of a 7 bytes optimization now. I did manually optimize that piece of code, and the bytes they remove will break it.
The script has an id (`id="ScullyIO-transfer-state"`) so it should not be that hard to exclude that from the optimizer

**Comment by BrendanSluke** [comment] 2021-05-24 17:07
@SanderElias Thank you for the quick and excellent feedback!

I was able to fix my issue based on your insight, I am now able to use Cloudflare's caching functionality with Scully.

The solution was to go into the Speed/Optimization settings area and turn off Auto Minify for HTML files:
![image](https://user-images.githubusercontent.com/62220614/119383133-99fcfc80-bc88-11eb-99e2-fe8eada7f1c3.png)
