### ISSUE TITLE
Static route question

### ISSUE THREAD

**Issue by davthu** [scullyio/scully#773] opened 2020-07-22 11:15 UTC
How would you go about to create a static route with no child routes (slugs) and still have it to render content from a markdown file? Valid use case for this would be Static Pages like Home or About Us.

**Comment by msacket** [comment] 2020-07-22 19:17
You can use the `extraRoutes` configuration:

```javascript
exports.config = {
  projectRoot: "./src",
  projectName: "gammastream-web",
  outDir: './dist/static',
  extraRoutes: [
    '/',
    '/services',
    '/customers',
    '/pricing'
  ]
};

**Comment by davthu** [comment] 2020-07-22 19:53
@msacket What I’m trying to do is to use the Netlify CMS ”File Collections” configuration to edit single files rather than entire folders.

https://www.netlifycms.org/docs/collection-types/#file-collections

**Comment by SanderElias** [comment] 2020-07-23 07:06
That can be done by I plugin. I created one with Aaron and Jorge in one of our calls. Perhaps we should pull it in.
```typescript
import { registerPlugin, scullyConfig, ScullyConfig } from '@scullyio/scully';
import { join } from 'path';

const tadaaPlugin = registerPlugin('router', 'tadaa', async (route, config) => {
  console.log(join(scullyConfig.homeFolder, config.file));
  return [
    {
      route,
      templateFile: join(scullyConfig.homeFolder, config.file),
    },
  ];
});

export const config: ScullyConfig = {
  projectRoot: './src',
  projectName: 'directmarkdownpage',
  outDir: './dist/static',
  routes: {
    '/bar': {
      type: 'tadaa',
      file: './content/bar.md',
      postRenderers: ['contentFolder'],
    },
  },
};
```

**Comment by geromegrignon** [comment] 2020-07-23 12:41
> That can be done by a plugin. I created one with Aaron and Jorge in one of our calls. Perhaps we should pull it in.

It would be a great idea !

**Comment by belamrani** [comment] 2021-01-06 15:56
Hi ! I have the same usecase with Netlify CMS. @SanderElias could you please share the plugin you made in your exemple ?
Thank you very much :)

**Comment by SanderElias** [comment] 2021-01-06 16:02
@belamrani  The entire code for the plugin is in the message above. I would call it something different as  `tadaa` tho  ;)

**Comment by belamrani** [comment] 2021-01-06 16:35
@SanderElias ^^ ok  I thought there was something else that I missed because I tried several time on my project and it doesn't work for me :( .

If you have any idea that could help me :)  ? 

My config.ts file : 

```
import { registerPlugin, scullyConfig, ScullyConfig } from '@scullyio/scully';
import { join } from 'path';

registerPlugin('router', 'static',  (route, config) => {
  console.log(join(scullyConfig.homeFolder, config.file));
  return [
    {
      route,
      templateFile: join(scullyConfig.homeFolder, config.file),
      postRenderers: ['contentFolder'],
    },
  ];
});

export const config: ScullyConfig = {
  projectRoot: './projects/slk/src',
  projectName: 'slk',
  outDir: './dist/static',
  routes: {
    '/home': {
      type: 'static',
      file: './contents/pages/home.md',
    }
  }
};
```

In scully-routes.json I have only this {"route":"/home"}

PS: I have other .md blog files in this project and it works perfectly.

Thank you

**Comment by belamrani** [comment] 2021-01-06 17:31
If I add data, like in the following exemple, the data are well added  : {"route":"/home","title":"Hello","test":"test"}

```
import {registerPlugin, scullyConfig, ScullyConfig} from '@scullyio/scully';
import {join} from 'path';

const staticPlugin = registerPlugin('router', 'static', async (route, config) => {
  console.log(join(scullyConfig.homeFolder, config.file));
  return [
    {
      route,
      templateFile: join(scullyConfig.homeFolder, config.file),
      postRenderers: ['contentFolder'],
      title: 'Hello',
      data : {
        test: 'test'
      }
    },
  ];
});

export const config: ScullyConfig = {
  projectRoot: './projects/slk-automobile/src',
  projectName: 'slk-automobile',
  outDir: './dist/static',
  routes: {
    '/home': {
      type: 'static',
      file: './contents/pages/home.md',
    },

  },
};
```

I can't find why the content of the .md file is not added in the scully-routes.json.

**Comment by SanderElias** [comment] 2021-01-07 09:21
@belamrani I just double-checked. [here](https://github.com/aaronfrost/directmarkdownpage/tree/markdownOnRoot) is my updated branch of the repo where we did test this. I updated t to the latest of angular and Scully, and it still works as expected.

**Comment by adrian-ub** [comment] 2021-02-06 00:18
I tried add meta 

```typescript
const templateFile = join(scullyConfig.homeFolder, config.file);
const { meta } = await readFileAndCheckPrePublishSlug(templateFile);
return [
    {
      route,
      templateFile,
      data: meta,
      postRenderers: ['contentFolder'],
    },
  ];
```

and return error: 
```
The plugin 'staticFile' needs to return handledRoutes with a route that starts with '/'. The route {"route":"","templateFile":"G:\\projects\\adrianub\\website\\libs\\content\\src\\lib\\pages\\index.md","data":{"title":"Este es el titulo"},"postRenderers":["contentFolder"]} is invalid.
```

any solution?

**Comment by SanderElias** [comment] 2022-03-25 09:41
Closing due to lack of actionable context. If this still is an issue, can you provide a minimal repo that reproduces this behavior? We will gladly reopen and work out the issue

**Closed by SanderElias** 2022-03-25 09:41 UTC
Labels: help wanted, plugins
