### ISSUE TITLE
CI/CD Process Fails on Gitlab

### ISSUE THREAD

**Issue by aniketdharia** [scullyio/scully#474] opened 2020-04-17 09:48 UTC
## 🐞 Bug report
when trying to run npm run scully via yml file the server

### Description
> scully
  ☺   new Angular build imported
  ☺   Started servers in background
 Could not connect to server
 npm ERR! code ELIFECYCLE
 npm ERR! errno 15
 npm ERR! india-covid-19@0.0.1 scully: `scully`
 npm ERR! Exit status 15
 npm ERR! 
 npm ERR! Failed at the india-covid-19@0.0.1 scully script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2020-04-17T09_14_38_289Z-debug.log

#### 💻Your Environment

**Angular Version:**
8.X.X
<pre><code>

</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by SanderElias** [comment] 2020-04-17 11:52
Duplicate of #461 
Closing to focus communication in there

**Closed by SanderElias** 2020-04-17 11:52 UTC
Labels: bug
