### ISSUE TITLE
Schematic input validation error with Angular CLI 11 project

### ISSUE THREAD

**Issue by bampakoa** [scullyio/scully#1124] opened 2020-11-15 08:42 UTC
## 🐞 Bug report
When I install Scully in an Angular CLI 11 application, I get a schematic input validation error.

#### 🔬 Minimal Reproduction

1. Create a new Angular CLI project with `ng new my-app --routing`
2. Install Scully with `ng add @scullyio/init`

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 11.0.1
Node: 12.19.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.1 (cli-only)
@angular-devkit/core         11.0.1 (cli-only)
@angular-devkit/schematics   11.0.1 (cli-only)
@schematics/angular          11.0.1 (cli-only)
@schematics/update           0.1100.1 (cli-only)
</code></pre>

**Scully Version:**

<pre><code>

 "@scullyio/init": "^1.0.1",
 "@scullyio/ng-lib": "^1.0.0",
 "@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>

```
Schematic input does not validate against the Schema: "my-app"
Errors:

  Data path "" should be object.
```
</code></pre>

**Comment by SanderElias** [comment] 2020-11-16 15:00
Duplicate of #1126. 
(I knew this is older, but I'm going to focus communication there.)
Seems related to CLI 11.

**Closed by SanderElias** 2020-11-16 15:00 UTC
Labels: bug
