### ISSUE TITLE
Couldn't find a route declaration in /src/app/app.module.ts

### ISSUE THREAD

**Issue by IxquitilisSaid** [scullyio/scully#36] opened 2019-12-17 10:37 UTC
Since `ng g @scullyio/init:blog` requires a route declaration, should the [Blog](https://github.com/scullyio/scully/blob/master/docs/blog.md) Doc contain an "observation" so the user has the AppRoutingModule import? Or is it not required and I'm missing something? 

Have a great day and Team Scully all the way!

**Comment by jorgeucano** [comment] 2019-12-17 13:10
hey, have a great day you to @IxquitilisSaid !
Can you show me an example?

**Comment by IxquitilisSaid** [comment] 2019-12-17 13:53
Certainly! https://github.com/IxquitilisSaid/ScullyNoRouter 

**Steps taken** 

- Generated new Angular Project with `ng n` script
- On "Do you wish to add Angular Routing?" typed "n"
- Ran `ng add @scullyio/init`
- Ran `ng g @scullyio/init:blog`

**Result:** `Couldn't find a route declaration in /src/app/app.module.ts.`

**To note:** When I ran into this issue, I made a new project but included the Angular Router, which worked fine.

I can also include the one that worked if that helps 😄!

**Comment by jorgeucano** [comment] 2019-12-17 13:55
Ohhh the angular route is needed, that's the problem!
@Villanuevand Can you add this to the doc?? 

thanks!

**Comment by IxquitilisSaid** [comment] 2019-12-17 14:05
Makes sense since the scully.config needs the Routes object, but yeah, just a small bit of documentation missing 😜.

Also please let me know if I can help out with anything else, I'm really excited about this project and what's to come!

**Comment by jorgeucano** [comment] 2019-12-17 14:07
thanks @IxquitilisSaid, I think start to use it and check if you found bugs is the best option now for help us!

**Comment by SanderElias** [comment] 2019-12-18 06:25
@aaronfrost  Do you think we need to add some more content/context to that error, aside form mentioning this in the documentation?

**Comment by SanderElias** [comment] 2019-12-18 10:59
@IxquitilisSaid I'm closing this, because it works as designed. 
However, we tok notes, and will update the docs and the error message to be more clear on this.

**Closed by SanderElias** 2019-12-18 10:59 UTC
Labels: documentation
