### ISSUE TITLE
Properties returned from ScullyRoutesService getCurrent() undefined when switching posts

### ISSUE THREAD

**Issue by tomling** [scullyio/scully#1118] opened 2020-11-09 16:44 UTC
### Description

I have an issue with getting properties from ScullyRoutesService getCurrent() when running the app in prod mode.

When I initially go to a post, the ScullyRoutesService getCurrent() method returns a list of properties that I can use on the page (such as the page title). When I go back and navigate to a different route, these properties are then undefined. This problem can only be replicated when the app is built in prod mode.  

I am fairly new to Angular, so this could be an implementation problem rather than a bug with Scully. 

#### 🔬 Minimal Reproduction

I have created a repo with the bug present - https://github.com/tomling/scully-app

When running the app in prod mode, go to News -> Click one of the links. You can see the date displayed at the top of the post.
Then go back to the News page, then click another post. The date now does not appear. 
The only way of returning the date is by navigating back to a post and refreshing the page.

#### 💻Your Environment

**Angular Version:**

Angular CLI: 10.1.7
Node: 14.8.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.5

**Scully Version:**

"@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.4",

## 🔥 Exception or Error

No visible error

**Comment by SanderElias** [comment] 2020-11-09 16:53
Sounds like you lost a subscription or something. Are you sure you don't have a `first` or `take(1)` in there somewhere? Are you using guards for this?
If not, I'll take a look at your app tomorrow.

**Comment by tomling** [comment] 2020-11-09 17:05
I haven't got any route guards and no calls to those specific operations.

The app is fairly basic and as I am fairly new to Angular, this could completely be down to my implementation... but some help would be very much appreciated 😊

**Comment by SanderElias** [comment] 2020-11-10 07:42
@tomling 
Problem turns to be something in your template:
I changed it to this:
```html
<div class="py-5" *ngIf="post$ | async as route">
  <p>{{ route.publishedAt | date: "dd MMMM yyyy" }}</p>
</div>
<div class="py-5">
  <!-- This is where Scully will inject the static HTML -->
  <scully-content></scully-content>
</div>
```
and now it is showing properly.

I did this in your controller:
```typescript
export class NewsComponent implements OnInit {
  post$ = this.scully
    .getCurrent()
    .pipe(tap((r) => console.log('currentRoute', r)));

  constructor(private scully: ScullyRoutesService) {}

  ngOnInit(): void {}
}
```
there is no reason to assign the observable (a function itself) inside the ngOnInit.
But mostly I added the tap to see what was going on. (you can remove that)
And it turns out, the `getCurrent()` is working as expected. When you do this, you will see the data in your console, but not in your view. 

I'm going to close this issue because the `getCurrent()` is working as expected. But feel free to open a new issue. There is something strange there indeed, but I don't think the issue is coming from Scully.

**Closed by SanderElias** 2020-11-10 07:42 UTC
Labels: bug
