### ISSUE TITLE
Invalid content-type. Expected application/json but received text/html; charset=UTF-8

### ISSUE THREAD

**Issue by beeman** [scullyio/scully#92] opened 2019-12-24 20:32 UTC
# 🐞 Bug report

### Description

I'm running into an issue where I can't get Scully to run in my project.

It looks like it can't connect to Puppeteer, though that's a wild guess.

A repro can be found in [this repo](https://github.com/beeman/scully-starter). In order to make sure it's not something on my local machine I've added a Docker configuration that shows the issue.

## 🔬 Minimal Reproduction

In order to get this error:

```
git clone https://github.com/beeman/scully-starter
cd scully-starter
yarn docker:build
```

<pre><code>
.....DOCKER BUILD OUTPUT HERE.....
$ scully
The option outFolder isn't configures, we are using "/workspace/dist/static/ by default now"
Cleaned up /workspace/dist/static/ folder.
 ☺   new Angular build imported
started servers in background
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Invalid content-type.
Expected application/json but received text/html; charset=UTF-8
Could not connect to server</code></pre>

## 💻Your Environment 
**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.7
Node: 12.12.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "0.0.9",
    "@scullyio/ng-lib": "0.0.7",
    "@scullyio/scully": "0.0.46",</code></pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Splaktar** [comment] 2019-12-26 22:30
I had a similar issue (reported in https://github.com/scullyio/scully/issues/31), but the root cause turned out to be a lack of support for catch all routes (mine went to a `PageNotFoundComponent`).

Since you don't have any catch all routes, it's likely something to do with how [you have](https://github.com/beeman/scully-starter/blob/master/src/app/app.routes.ts) your root component and child component configured with the `''` path.

**Comment by beeman** [comment] 2019-12-27 06:14
That's a good point @Splaktar, I will check to see if changing that fixes it.

**Comment by SanderElias** [comment] 2019-12-31 17:18
Closing to focus discussion in #31

**Closed by SanderElias** 2019-12-31 17:18 UTC
Labels: bug

**Comment by Arman-91** [comment] 2022-03-16 08:53
https://kazicap.atlassian.net
