### ISSUE TITLE
Scully process getting stuck after render the files

### ISSUE THREAD

**Issue by lucasvieirasilva** [scullyio/scully#1396] opened 2021-06-25 13:05 UTC
### Description

There is an intermittent issue when running the `npx scully` to render the page, after the message `Generating took x seconds for x pages` the process stays stuck, and to close it is necessary to send a signal to the terminal (e.g. `ctrl+c`).

That impacts in a very bad way the CI/CD process, then I found this fix https://github.com/scullyio/scully/pull/1334 that runs the `process.exit(0)` statement to prevent CI/CD stall, after some tests I have noticed that the `serve` process on port `1864` still open, looking at the Scully source code I have seen the file changed in the PR https://github.com/scullyio/scully/pull/1334 is not the root one, there is another javascript that waits for this execution being completed (https://github.com/scullyio/scully/blob/main/libs/scully/src/scully.ts#L163) to run the `/killMe` HTTP GET to close the server (https://github.com/scullyio/scully/blob/main/libs/scully/src/scully.ts#L166).

So, if you run two Scully projects in sequence, the second one will use the angular server from the first execution, causing bad rendered files.

#### 🔬 Minimal Reproduction

Execution being stuck:

With the `1.1.1` version
![image](https://user-images.githubusercontent.com/12723594/123428205-f01cd280-d59b-11eb-9d3e-dd72c4531078.png)

After the message `Generating took x seconds for x pages` be presented, I have open another terminal tab and run this command `sudo lsof -i :1864`

![image](https://user-images.githubusercontent.com/12723594/123428525-4853d480-d59c-11eb-84c5-a46cbae3d8e1.png)

Then I run the command `kill -9 PID` and the Scully execution finishes  

![image](https://user-images.githubusercontent.com/12723594/123428647-67eafd00-d59c-11eb-9ebd-ab43b71fff24.png)

With the beta version `1.1.1-BETA.140239` the process finishes but the server still open in the port `1864`

![image](https://user-images.githubusercontent.com/12723594/123428933-b7c9c400-d59c-11eb-8a45-c8a86d24678d.png)

So, if I run another Scully CLI using a different project the render pages will be based on this first project.

#### 💻Your Environment

**Angular Version:**

```shell
Angular CLI: 11.2.4
Node: 12.22.1
OS: darwin x64

Angular: 11.2.14
... common, core
Ivy Workspace: <error>

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1102.4
@angular-devkit/build-angular       0.1102.4
@angular-devkit/core                11.2.4
@angular-devkit/schematics          11.2.4
@angular/animations                 11.2.7
@angular/cdk                        11.2.4
@angular/cli                        11.2.4
@angular/compiler                   11.2.5
@angular/compiler-cli               11.2.5
@angular/forms                      11.2.7
@angular/language-service           11.2.5
@angular/platform-browser           11.2.7
@angular/platform-browser-dynamic   11.2.5
@angular/platform-server            11.2.5
@angular/router                     11.2.5
@schematics/angular                 11.2.4
@schematics/update                  0.1102.4
rxjs                                6.6.3
typescript                          4.1.3
```
**Scully Version:**

```text
"@scullyio/scully": "1.1.1",
```
and the beta version that I have tested this PR https://github.com/scullyio/scully/blob/main/libs/scully/src/scully.ts#L166 changes

```text
"@scullyio/scully": "1.1.1-BETA.140239",
```

## 🔥 Exception or Error

No exception, the process just does not finish.

**Comment by SanderElias** [comment] 2021-06-28 11:53
closing as duplicate of #1348

**Closed by SanderElias** 2021-06-28 11:53 UTC
Labels: bug
