### ISSUE TITLE
npm run scully (Getting count not connect to server)

### ISSUE THREAD

**Issue by mbaljeetsingh** [scullyio/scully#57] opened 2019-12-19 11:00 UTC
# 🐞 Bug report
![image](https://user-images.githubusercontent.com/872762/71168182-27f6db80-227c-11ea-901d-2a2d20d73bc1.png)

### Description
`dist/static` folder is not being generated. `npm run scully` stucks at started servers in backend and after sometime it disconnects while showing Could not connect to server. It was working sometime ago, suddenly stopped working. I'm using windows 10.

Getting the same issue inside netlify too, it was building there too,
![image](https://user-images.githubusercontent.com/872762/71168388-99368e80-227c-11ea-9818-9087934e5de4.png)

## 💻Your Environment 
**Angular Version:**
`^9.0.0-rc.7`

**Scully Version:**
`"@scullyio/init": "0.0.8",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "0.0.45",`

**Comment by SanderElias** [comment] 2019-12-19 14:06
duplicate of #40

**Closed by SanderElias** 2019-12-19 14:06 UTC
Labels: bug
