### ISSUE TITLE
Don't display <scully-content> with Japanese URL Fragment

### ISSUE THREAD

**Issue by c-su** [scullyio/scully#1393] opened 2021-06-19 02:47 UTC
### Description

If you enter a URL fragment once and then change it to a Japanese URL fragment, scully-content will not be displayed.

#### Before
<img width="930" alt="スクリーンショット 2021-06-19 10 58 00" src="https://user-images.githubusercontent.com/4987854/122628905-ffab9f80-d0f3-11eb-918b-83925314bfe2.png">

#### After
<img width="979" alt="スクリーンショット 2021-06-19 10 58 12" src="https://user-images.githubusercontent.com/4987854/122628912-09cd9e00-d0f4-11eb-8b90-d230194081e7.png">

#### 🔬 Minimal Reproduction

```
$ ng new my-app && cd my-app

$ ng add @scullyio/init

$ ng generate @scullyio/init:blog

$ npm run build && npm run scully

$ npm run scully:serve
```

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 11.0.7
Node: 12.20.0
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.7
typescript                      4.0.8

</code></pre>

**Scully Version:**

<pre><code>
{
  "name": "my-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.3",
    "@angular/common": "~11.0.3",
    "@angular/compiler": "~11.0.3",
    "@angular/core": "~11.0.3",
    "@angular/forms": "~11.0.3",
    "@angular/platform-browser": "~11.0.3",
    "@angular/platform-browser-dynamic": "~11.0.3",
    "@angular/router": "~11.0.3",
    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.3",
    "@angular/cli": "~11.0.3",
    "@angular/compiler-cli": "~11.0.3",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
</code></pre>

## 🔥 Exception or Error

Nothing.

**Comment by Jefiozie** [comment] 2021-06-19 07:21
Hi @c-su, thank you for reporting the issue. Would it be possible to share a reproduction so that we easily can investigate the issue?

Thanks

**Comment by SanderElias** [comment] 2021-06-22 14:18
I'm going to close this because we can't reproduce.
We are more as happy to reopen the issue as a we get an proper way to reproduce the issue

**Closed by SanderElias** 2021-06-22 14:18 UTC
Labels: bug
