### ISSUE TITLE
yarn test fails

### ISSUE THREAD

**Issue by kkweon** [scullyio/scully#697] opened 2020-07-06 01:43 UTC
### Description
- `yarn test` fails at the main branch

#### 🔬 Minimal Reproduction
- yarn test

#### 💻Your Environment

**Angular Version:** 

<pre><code>

❯ ng --version
Your global Angular CLI version (10.0.1) is greater than your local
version (9.1.10). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.10
Node: 12.18.0
OS: darwin x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.10
@angular-devkit/build-ng-packagr   0.901.10
@angular-devkit/build-optimizer    0.901.10
@angular-devkit/build-webpack      0.901.10
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@angular/cli                       9.1.10
@ngtools/webpack                   9.1.10
@schematics/angular                9.1.10
@schematics/update                 0.901.10
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Scully Version:** main branch

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>
❯ yarn test
yarn run v1.22.4
$ run-s build:scully server:kill build:code symlinks server:testDocs server:wait build:docs server:kill server:testSample server:wait build:sample  jest:test cypress:e2e
$ nx build scully --prod

> nx run scully:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library scully...
Done compiling TypeScript files for library scully
Copying asset files...
Done copying asset files.
$ npm run scully -- killServer
npm WARN lifecycle The node binary used for scripts is /var/folders/8v/5ldr1m7x1d7ctc8r2d9s5rkh00mr18/T/yarn--1593999750897-0.10891427743965743/node but npm is using /Users/kkweon/.nvm/versions/node/v12.18.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> scullyio@0.0.0 scully /Users/kkweon/github/scully
> node ./dist/libs/scully/scully.js "killServer"

---------
    Config file "./scully.undefined.config.ts" not found, only rendering routes without parameters
    The config file should have a name that is formated as:
       scully.<projectName>.config.ts
    where <projectName> is the name of the project as defined in the 'angular.json' file
    When you are in a mixed mono-repo you might need to use the --pjFirst flag.
---------

Could not find project "undefined" in 'angular.json'.
****************************************************************************************
This is a development tool for Scully applications.
You can ignore the warning (TLS) or run scully with --no-warning
****************************************************************************************
(node:50730) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Sent kill command to server
$ nx run-many --parallel --target=build --all --prod

>  NX  Running target build for projects:

  - plugins-scully-plugin-flash-prevention
  - plugins-base-href-rewrite
  - scully-schematics
  - plugins-from-data
  - plugins-logrocket
  - plugins-extra
  - sample-blog
  - scully-docs
  - scully
  - ng-lib

———————————————————————————————————————————————

> nx run scully:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library scully...
Done compiling TypeScript files for library scully
Copying asset files...
Done copying asset files.

> nx run ng-lib:build:production

>  NX   NOTE  Cached Output:

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@scullyio/ng-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Writing package metadata
Built @scullyio/ng-lib

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/kkweon/github/scully/libs/ng-lib
 - to:   /Users/kkweon/github/scully/dist/libs/ng-lib
------------------------------------------------------------------------------

> nx run plugins-scully-plugin-flash-prevention:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library plugins-scully-plugin-flash-prevention...
Done compiling TypeScript files for library plugins-scully-plugin-flash-prevention
Copying asset files...
Done copying asset files.

> nx run plugins-base-href-rewrite:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library plugins-base-href-rewrite...
Done compiling TypeScript files for library plugins-base-href-rewrite
Copying asset files...
Done copying asset files.

> nx run plugins-from-data:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library plugins-from-data...
Done compiling TypeScript files for library plugins-from-data
Copying asset files...
Done copying asset files.

> nx run plugins-logrocket:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library plugins-logrocket...
Done compiling TypeScript files for library plugins-logrocket
Copying asset files...
Done copying asset files.

> nx run plugins-extra:build

>  NX   NOTE  Cached Output:

Compiling TypeScript files for library plugins-extra...
Done compiling TypeScript files for library plugins-extra
Copying asset files...
Done copying asset files.

> nx run sample-blog:build:production

>  NX   NOTE  Cached Output:

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {3} polyfills-es5.js (polyfills-es5) 130 kB [initial] [rendered]
chunk {2} polyfills-es2015.js (polyfills) 37.4 kB [initial] [rendered]
chunk {1} main-es2015.js (main) 274 kB [initial] [rendered]
chunk {1} main-es5.js (main) 331 kB [initial] [rendered]
chunk {5} 5-es2015.js () 1.02 kB  [rendered]
chunk {5} 5-es5.js () 1.67 kB  [rendered]
chunk {0} runtime-es2015.js (runtime) 2.2 kB [entry] [rendered]
chunk {0} runtime-es5.js (runtime) 2.2 kB [entry] [rendered]
chunk {6} 6-es2015.js () 1.3 kB  [rendered]
chunk {6} 6-es5.js () 1.89 kB  [rendered]
chunk {9} 9-es2015.js () 803 bytes  [rendered]
chunk {9} 9-es5.js () 1.25 kB  [rendered]
chunk {12} 12-es2015.js () 1.19 kB  [rendered]
chunk {12} 12-es5.js () 1.33 kB  [rendered]
chunk {7} 7-es2015.js () 2.96 kB  [rendered]
chunk {7} 7-es5.js () 3.64 kB  [rendered]
chunk {11} 11-es2015.js () 772 bytes  [rendered]
chunk {11} 11-es5.js () 1.23 kB  [rendered]
chunk {10} 10-es2015.js () 1.03 kB  [rendered]
chunk {10} 10-es5.js () 1.54 kB  [rendered]
chunk {13} 13-es2015.js () 3.27 kB  [rendered]
chunk {13} 13-es5.js () 3.83 kB  [rendered]
chunk {14} 14-es2015.js () 7.55 kB  [rendered]
chunk {14} 14-es5.js () 8.59 kB  [rendered]
chunk {8} 8-es2015.js () 1.54 kB  [rendered]
chunk {8} 8-es5.js () 2.04 kB  [rendered]
chunk {4} styles.css (styles) 1.68 kB [initial] [rendered]
Date: 2020-07-06T01:33:22.578Z - Hash: 37c7a40bd6c62fc3f665 - Time: 18388ms

> nx run scully-docs:build:production

>  NX   NOTE  Cached Output:

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {3} polyfills-es5.0104d220b432e47b65c2.js (polyfills-es5) 130 kB [initial] [rendered]
chunk {2} polyfills-es2015.1636f6930dd2a9127f71.js (polyfills) 37.4 kB [initial] [rendered]
chunk {0} runtime-es2015.8d2168751328d6fbb863.js (runtime) 2.26 kB [entry] [rendered]
chunk {0} runtime-es5.8d2168751328d6fbb863.js (runtime) 2.26 kB [entry] [rendered]
chunk {5} 5-es2015.8fa00dbc500b133f9a33.js () 9.35 kB  [rendered]
chunk {5} 5-es5.8fa00dbc500b133f9a33.js () 9.98 kB  [rendered]
chunk {1} main-es2015.45254d263454a1c7bcf3.js (main) 319 kB [initial] [rendered]
chunk {1} main-es5.45254d263454a1c7bcf3.js (main) 386 kB [initial] [rendered]
chunk {6} 6-es2015.3c575a6c889599665ffe.js () 3.93 kB  [rendered]
chunk {6} 6-es5.3c575a6c889599665ffe.js () 5.66 kB  [rendered]
chunk {4} styles.bf691284a175e9825a45.css (styles) 6.01 kB [initial] [rendered]
Date: 2020-07-06T01:33:22.199Z - Hash: 3d8c235113bce2105b40 - Time: 18019ms
libs/scully-schematics/src/add-post/index.ts:42:9 - error TS2322: Type 'string | object' is not assignable to type '{ title: string; description: string; published: boolean; }'.
  Type 'string' is not assignable to type '{ title: string; description: string; published: boolean; }'.

42         metaData = metaDataAsJson;
           ~~~~~~~~


Found 1 error.


> nx run scully-schematics:build
Compiling TypeScript files for library scully-schematics...

———————————————————————————————————————————————

>  NX   ERROR  Running target "build" failed

  Failed projects:

  - scully-schematics

  You can isolate the above projects by passing: --only-failed

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:code" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</code></pre>

**Comment by SanderElias** [comment] 2020-07-06 02:04
I just checked, tests are passing for me, and in our github action, that would block merging anything into main, if any of the tests would fail. 
Currently, we are using NPM and not Yarn. Perhaps that is why it doesn't build on your machine?
I have seen stuff like this happen when the local `node_modules` contained incompatible packages. an `npm ci` would usually fix that.

Closing as we can't reproduce

**Closed by SanderElias** 2020-07-06 02:04 UTC
Labels: bug

**Comment by kkweon** [comment] 2020-07-06 04:31
Thank you for the response @SanderElias 🙏 

Indeed, it works with npm. But not with the yarn (I can consistently reproduce using the yarn).

Could you please consider removing **[yarn.lock](https://github.com/scullyio/scully/blob/main/yarn.lock)** if yarn is not supposed to be used in the project?

I think the root cause of this is that yarn.lock is outdated and needs update.


```
❯ rm -rf node_modules && yarn install --frozen-lockfile
yarn install v1.22.4

# you can see the warning message as well

warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning @types/path-to-regexp@1.7.0: This is a stub types definition for path-to-regexp (https://github.com/pillarjs/path-to-regexp). path-to-regexp provides its own type definitions, so you don't need @types/path-to-regexp installed!
warning tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

When a yarn is used, it picks up a different version of js-yaml (3.12.4 -> 3.12.5) that its return type became more explicit recently (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/14f1fea4b0d0ebbb9d0c24515b0de424d1e811b4#diff-04f6016a036302b33275b2bf3b57f9d7), which results in the above error I was experiencing.

**Comment by SanderElias** [comment] 2020-07-06 11:38
@kkweon I just found out today that one slipped in. That will be removed. Thanks for reporting this.
After double-checking, you are right, and even if you completely remove the yarn.lock and update it, there is still an error. 
For now, I will leave it at this, but I will discuss this in the team tomorrow.
