### ISSUE TITLE
Cannot read property 'search' of null

### ISSUE THREAD

**Issue by TGihan** [scullyio/scully#1168] opened 2020-12-13 09:40 UTC
### Description
`ng add  @scullyio/init` finished with the error `Cannot read property 'search' of null` and `scully.<projectName>.config.ts` file is not created in the project

#### 🔬 Minimal Reproduction
1. ng add  @scullyio/init

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.1.12
Node: 14.15.1
OS: win32 x64

Angular: 9.0.4
... common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.9
@angular-devkit/build-optimizer    0.901.9
@angular-devkit/build-webpack      0.901.9
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@angular/animations                9.1.12
@angular/cdk                       9.2.4
@angular/cli                       9.1.12
@angular/fire                      5.4.2
@angular/flex-layout               9.0.0-beta.31
@angular/http                      4.4.6
@angular/material                  9.2.4
@angular/material-moment-adapter   7.3.7
@angular/youtube-player            11.0.0
@ngtools/webpack                   9.1.9
@nguniversal/express-engine        7.0.2
@schematics/angular                9.0.4
@schematics/update                 0.901.12
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.42.0

</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "^1.0.1"

</code></pre>

## 🔥 Exception or Error

<pre><code>
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Cannot read property 'search' of null

</code></pre>

**Comment by SanderElias** [comment] 2020-12-14 07:47
I have found no way to reproduce this issue. @jorgeucano can you test on windows?

**Comment by SanderElias** [comment] 2020-12-16 13:44
@TGihan Jorge did do a check on windows too, and we can't reproduce. That means there is not much we can do.
If you have a way for us to reproduce your issue, I will gladly reopen this issue, but for now, I'm going to close it.

**Comment by flack** [comment] 2021-03-05 13:29
just to let you know, I'm seeing the same problem:

```
$ ng add @scullyio/init
ℹ Using package manager: npm
✔ Found compatible package version: @scullyio/init@1.1.1.
✔ Package information loaded.
✔ Package successfully installed.
Cannot read property 'search' of null
```

```
Angular CLI: 11.2.3
Node: 12.18.2
OS: linux x64

Angular: 11.2.4
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
typescript                      4.0.7
```

is there any way to get more debugging output?

**Comment by SanderElias** [comment] 2021-03-05 13:59
@jorgeucano Can you take a look?

**Comment by SanderElias** [comment] 2021-03-08 08:48
@TGihan @flack This problem occurs if the `angular.json` file doesn't have its default project set correctly.
you can execute Scully with the `--projectName myProjectname` flag

**Comment by flack** [comment] 2021-03-10 10:29
@SanderElias maybe I'm doing it wrong, but I added `"defaultProject": "myproject"` to the top level of `angular.json`. However, I still get the same error:

```
$ ng add @scullyio/init                
ℹ Using package manager: npm
✔ Found compatible package version: @scullyio/init@1.1.1.
✔ Package information loaded.
✔ Package successfully installed.
Cannot read property 'search' of null
```

**Comment by SanderElias** [comment] 2021-03-11 16:34
@flack Does it work for you when you use the flag?
```bash
 ng add @scullyio/init   --project myproject
```

**Comment by flack** [comment] 2021-03-11 17:02
@SanderElias nope, produces exactly the same output:

```
$ ng add @scullyio/init  --project myproject  
ℹ Using package manager: npm
✔ Found compatible package version: @scullyio/init@1.1.1.
✔ Package information loaded.
✔ Package successfully installed.
Cannot read property 'search' of null
```

I also tried to run the command on a fresh angular project (separate directory, created with `ng new`), the idea being that I can just copy over the changes it makes. In the new project I don't get this error, but I run into #1288 instead, so I still can't get anything running. Is there a way to do the setup by hand?

**Comment by SanderElias** [comment] 2021-03-12 13:05
@flack Can you give me access to your project? That way I can see what's going on in there.
For 1288, there is a solution in there already. and Jorge will take a look at what's going on.

**Comment by SanderElias** [comment] 2021-05-29 10:06
Iḿ closing this, as I believe this problem is solved now. If I'm mistaken, let m know and I will reopen it

**Closed by SanderElias** 2021-05-29 10:06 UTC
Labels: bug

**Comment by alessandro-tucci-visiontech** [comment] 2021-07-13 10:31
My two cents: as per what I found while dealing with this analoguous issue (#1402) , it may be due to a couple of Scully's implicit requirements:

1. @angular/core shall be explicitly listed in the _dependencies_ section of your package.json file, e.g.
```
  "dependencies": {
    "@angular/core": "~11.2.14",
    [..]
  }
```
2. Your package.json file shall contain a _scripts_ section. If you don't have any script to list, declare it empty,
```
{
  [..]
  "dependencies": {
    [..]
  },
  "devDependencies": {
    [..]
  },
  "scripts": {}
}
```
