### ISSUE TITLE
Error during file write

### ISSUE THREAD

**Issue by flauc** [scullyio/scully#459] opened 2020-04-11 22:16 UTC
## 🐞 Bug report

This is the error I'm getting
`Error during file write TypeError: Cannot read property 'includes' of undefined`. This is the stack trace.

![image](https://user-images.githubusercontent.com/4489834/79055951-7b3cd180-7c51-11ea-93bf-441ec9c4336b.png)

### Description

Running `scully` generates all the expected files, but any of the routes defined in `scully.config.js` are generated with `undefined` content. 

The project has a few Scully recommended plugins added, but even when all of them are commented out the same error occurs. It's also not various resolvers attached to some of those pages because commenting them out also doesn't resolve the issue. 

#### 🔬 Minimal Reproduction

It's a public project 
https://github.com/Jaspero
Each of the posts is generated as undefined
https://github.com/Jaspero/exo/blob/master/public/blog/2020-03-16-blog/index.html

Run 
1. `npm run build`
2. `npm run scully`

This would just build the angular app and then run `scully` on top of it.

#### 💻Your Environment

Windows 10 (but this also happens in the CI/CD pipeline which is an ubuntu server) 

**Angular Version:**

<pre><code>9.0.6</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "0.0.23",
    "@scullyio/ng-lib": "0.0.22",
    "@scullyio/scully": "0.0.86",
</code></pre>

## 🔥 Exception or Error

Below is just one of the examples. It happens for every route. 

<pre><code>
TypeError: Cannot read property 'split' of undefined
    at contentRenderPlugin (C:\Users\filip\Desktop\projects\github\exo\app\node_modules\@scullyio\scully\renderPlugins\contentRenderPlugin.js:22:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async wrap (C:\Users\filip\Desktop\projects\github\exo\app\node_modules\@scullyio\scully\pluginManagement\pluginRepository.js:69:18)
    at async C:\Users\filip\Desktop\projects\github\exo\app\node_modules\@scullyio\scully\renderPlugins\routeContentRenderer.js:16:24
    at async C:\Users\filip\Desktop\projects\github\exo\app\node_modules\@scullyio\scully\renderPlugins\routeContentRenderer.js:11:22
Error during content generation with plugin "minifyHtml" for C:\Users\filip\Desktop\projects\github\exo\app\dist\collections\shop\soap-and-creme.md. This hander is skipped.
Route "/shop/soap-and-creme" rendered into file: "C:\Users\filip\Desktop\projects\github\exo\app\dist\static\shop\soap-and-creme\index.html"
/shop/soap-and-creme undefined
Error during file write TypeError: Cannot read property 'includes' of undefined
</code></pre>

**Comment by SanderElias** [comment] 2020-04-13 06:45
Hi @flauc, When I download and run your app with `ng serve`, and navigate to `https://localhost:4200/blog/2020-03-16-blog` I get a block page.
When I then run `document.querySelector('sculy-content')`
I get:
![image](https://user-images.githubusercontent.com/1249083/79098654-bed33080-7d62-11ea-8752-1d2b4205b9ca.png)
This means the `scully-content` is not present, and Scully will not be able to inject the markdown content.

I'm closing this for now, as the root cause of your issue seems to be inside your app. I'm more as willing to reopen if needed

**Closed by SanderElias** 2020-04-13 06:45 UTC
Labels: bug

**Comment by flauc** [comment] 2020-04-13 10:12
@SanderElias thank you for looking into this. Yes, it looks like a resolver was preventing the page from rendering. Thanks!
